# -*- coding: UTF-8 -*-
from datetime import datetime

malePopulation = 0.6

NUtilizadores = 80
NMaquinas = 45
AVGVendasDia = 45
DesvioVendasDia = 10
DiasEntreRemessas = 2

initialBalance = [5] * 10 + [10] * 6 + [15] * 7 + [20] * 6 + [50] * 1

jobs = ["Construtor Civil"] * 10 + ["Electricista"] * 6 + ["Advogado"] * 7 + ["Estudante"] * 60 + ["Médico"] * 1 + ["Engenheiro"] * 1 + ["Dentista"] * 1 + ["Padeiro"] * 1 + ["Carteirista"] * 1 + ["Outro"] * 1



# Nome, precoA, precoV
produtos = [('Lanche','0.5', '0.8'),
            ('Bolacha Maria','0.2','0.4'),
            ('Bolacha Chocolate','0.7','1'),
            ('Croissant','0.3','0.5'),
            ('Kinder Bueno','0.4','0.7'),
            ('Kit Kat','0.3','0.55'),
            ('Ice Tea','0.5','0.8'),
            ('Agua','0.1','0.6'),
            ('Coca Cola','0.5','0.8')]

NProdutos = len(produtos)

# fstSell = datetime.strptime('2012-04-30', "%Y-%m-%d").date()
fstSell = datetime.strptime('2017-04-25', "%Y-%m-%d").date()
lstBuy = datetime.strptime('2017-04-30', "%Y-%m-%d").date()
sellingPeriod = lstBuy - fstSell

lstBornDate = datetime.strptime('1999-04-30', "%Y-%m-%d").date()
fstBornDate = datetime.strptime('1932-04-30', "%Y-%m-%d").date()
bornPeriod = lstBornDate - fstBornDate

male = ["Joaquim", "Júlio", "Artur", "João", "Miguel", "Leonardo", "José", "Carlos", "Alexandre", "Bernardo", "Daniel", "Eduardo", "Fernando", "Gabriel", "Hugo", "Ivo", "Luís", "Manuel", "Nuno", "Otávio", "Pedro", "Xavier", "Rui"]

female = ["Andreia", "Ana", "Filipa", "Beatriz", "Carolina", "Daniela", "Eduarda", "Fátima", "Gabriela", "Helena", "Ivone", "Joana", "Luísa", "Manuela", "Natália", "Patrícia", "Rita", "Sandra", "Vânia"]

surname = ["Abreu", "Aarão", "Alves", "Barros", "Campos", "Delgado", "Esteves", "Fernandes", "Gomes", "Henriques", "Infante", "Jesus", "Lima", "Lobo", "Machado", "Nestor", "Novais", "Nogueira", "Oliveira", "Pinto", "Pontes", "Pereira", "Rebelo", "Silva", "Raminhos", "Sá", "Rua", "Torres", "Teixeira", "Veiga", "Viana", "Vidal", "Xisto"]

sCharsReplacement = [("ã", "a"), ("â", "a"), ("á", "a"), ("é", "e"), ("ê", "e"), ("í", "i"), ("ó", "o"), ("ú", "u"), ("ç", "c")]

mailserver = ["gmail.com", "hotmail.com", "sapo.pt", "iol.pt", "outlook.com", "live.com.pt", "yahoo.com"]

machineModel = [("Cortex A", 18), ("Makita Serie 45", 23), ("StormKey", 16)]
machineRent = ["100", "200", "300", "250"]


adresses = [('3750-852','Largo de São Tiago','Aveiro','Águeda','Borralha'),
            ('3750-170','Urbanização do Alto do Rio','Aveiro','Águeda','Recardães'),
            ('3850-142','Viela Vacaria','Aveiro','Albergaria-a-Velha','Albergaria-A-Velha'),
            ('3850-451','Rua Várzea','Aveiro','Albergaria-a-Velha','Angeja'),
            ('3850-835','Rua do Sobreiral','Aveiro','Albergaria-a-Velha','Valmaior'),
            ('3780-306','Largo dos Combatentes da Grande Guerra','Aveiro','Anadia','Anadia'),
            ('3780-173','Rua da Labrusca','Aveiro','Anadia','Espairo'),
            ('4540-120','Rua Carlos Alves','Aveiro','Arouca','Arouca'),
            ('3810-27','Rua Mário Duarte','Aveiro','Aveiro','Aveiro'),
            ('3800-72','Rua de Rangel Quadros','Aveiro','Aveiro','Aveiro'),
            ('3810-157','Rua da República','Aveiro','Aveiro','Aveiro'),
            ('3800-85','Rua Fonte do Olho','Aveiro','Aveiro','Aveiro'),
            ('3810-894','Rua de Estarreja','Aveiro','Aveiro','Aveiro'),
            ('3800-601','Rua dos Pereiras','Aveiro','Aveiro','Sarrazola'),
            ('3810-600','Beco do Cruzeiro','Aveiro','Aveiro','Verba'),
            ('3800-853','Rua Chão de Baixo','Aveiro','Aveiro','Carregal'),
            ('4500-490','Rua do Mar','Aveiro','Espinho','Espinho'),
            ('4500-154','Rua 20','Aveiro','Espinho','Espinho'),
            ('4500-508','Rua Calvário','Aveiro','Espinho','Espinho'),
            ('3860-28','Rua dos Anjos','Aveiro','Estarreja','Avanca'),
            ('3865-18','Rua das Cavadas Sul','Aveiro','Estarreja','Canelas'),
            ('3865-127','Travessa da Rua da Costa','Aveiro','Estarreja','Fermelã'),
            ('3860-522','Beco dos Pescadores','Aveiro','Estarreja','Pardilhó'),
            ('3860-606','Rua 5 de Outubro','Aveiro','Estarreja','Veiros'),
            ('4505-710','Rua Fonte das Roçadas','Aveiro','Santa Maria da Feira','Argoncilhe'),
            ('3700-562','Rua Teixeira de Pascoais','Aveiro','Santa Maria da Feira','Arrifana'),
            ('4505-314','Rua do Bolhão','Aveiro','Santa Maria da Feira','Fiães'),
            ('4525-330','Rua do Monte','Aveiro','Santa Maria da Feira','Guisande'),
            ('4525-564','Travessa da Cruz','Aveiro','Santa Maria da Feira','Louredo'),
            ('3700-745','Rua Engenheiro Mário Hofle Araújo Moreira','Aveiro','Santa Maria da Feira','Seixal'),
            ('4500-748','Rua Liberdade','Aveiro','Santa Maria da Feira','Nogueira da Regedoura'),
            ('4505-657','Travessa do Camalhão','Aveiro','Santa Maria da Feira','Sanguedo'),
            ('4520-265','Rua Picalhos de Baixo','Aveiro','Santa Maria da Feira','Santa Maria da Feira'),
            ('4535-438','Rua António Gomes da Cruz','Aveiro','Santa Maria da Feira','Oleiros'),
            ('4525-498','Rua das Agras','Aveiro','Santa Maria da Feira','Vila Maior'),
            ('4525-84','Rua de Campêlo','Aveiro','Santa Maria da Feira','Campelo'),
            ('4520-108','Travessa Manuel Marque G.l. Resende','Aveiro','Santa Maria da Feira','Espargo'),
            ('3830-997','Rua Professor Francisco Corújo','Aveiro','Ílhavo','Gafanha da Encarnação'),
            ('3830-556','Beco do Café Carioca','Aveiro','Ílhavo','Gafanha da Nazaré'),
            ('3830-230','Travessa da Filarmónica Ilhavense','Aveiro','Ílhavo','Ílhavo'),
            ('3830-227','Rua Visconde Almeidinha','Aveiro','Ílhavo','Ílhavo'),
            ('3050-996','Rua Doutor Abel da Silva Lindo','Aveiro','Mealhada','Pampilhosa'),
            ('3870-156','Rua Alfredo Alferes','Aveiro','Murtosa','Murtosa'),
            ('3870-60','Estrada da Varela','Aveiro','Murtosa','Bunheiro'),
            ('3720-266','Rua da Quinta do Carrelhas','Aveiro','Oliveira de Azeméis','Oliveira de Azeméis'),
            ('3720-475','Rua da Estação','Aveiro','Oliveira de Azeméis','Fundo do Pinheiro'),
            ('3720-352','Travessa das Águas','Aveiro','Oliveira de Azeméis','Cucujães'),
            ('3720-93','Rua do Caima','Aveiro','Oliveira de Azeméis','Macinhata da Seixa'),
            ('3770-59','Rua da Fonte Doce','Aveiro','Oliveira do Bairro','Oiã'),
            ('3885-38','Travessa dos Castanheiros','Aveiro','Ovar','Arada'),
            ('3885-296','Rua do Rio Velho','Aveiro','Ovar','Cortegaça'),
            ('3885-616','Rua Professora Maria Joaquina Ferreira','Aveiro','Ovar','Esmoriz'),
            ('3885-824','Travessa da Fonte','Aveiro','Ovar','Maceda'),
            ('3880-995','Rua das Companhas','Aveiro','Ovar','Ovar'),
            ('3880-791','Travessa José das Dornas','Aveiro','Ovar','São João'),
            ('3880-550','Rua da Giesteira','Aveiro','Ovar','Válega'),
            ('3880-866','Rua dos Lopes','Aveiro','Ovar','São Vicente de Pereira Jusã'),
            ('3700-188','Travessa de Milheirós de Poiares','Aveiro','São João da Madeira','São João da Madeira'),
            ('3700-68','Avenida do Brasil','Aveiro','São João da Madeira','São João da Madeira'),
            ('3840-13','Rua da Amizade','Aveiro','Vagos','Cabecinhas'),
            ('3840-326','Estrada de São Tomé','Aveiro','Vagos','Ponte de Vagos'),
            ('3730-531','Rua do Barreiro','Aveiro','Vale de Cambra','Codal'),
            ('3730-259','Rua Manuel Soares Pinheiro','Aveiro','Vale de Cambra','Vale de Cambra'),
            ('7600-43','Largo Marquês de Pombal','Beja','Aljustrel','Aljustrel'),
            ('7600-408','Estrada de Aljustrel','Beja','Aljustrel','Montes Velhos'),
            ('7920-42','Travessa do Caturra','Beja','Alvito','Alvito'),
            ('7230-14','Rua Doutor Leite de Vasconcelos','Beja','Barrancos','Barrancos'),
            ('7800-312','Rua Doutor Manuel Marques da Costa','Beja','Beja','Beja'),
            ('7800-297','Rua de São Gregório','Beja','Beja','Beja'),
            ('7800-631','Travessa do Infantário','Beja','Beja','Cabeça Gorda'),
            ('7780-264','Travessa da Feira','Beja','Castro Verde','Castro Verde'),
            ('7780-483','Rua Vasco da Gama','Beja','Castro Verde','Sete'),
            ('7900-58','Rua Vasco da Gama','Beja','Ferreira do Alentejo','Alfundão'),
            ('7750-160','Rua do Norte','Beja','Mértola','Mina de São Domingos'),
            ('7885-30','Rua 1º de Maio','Beja','Moura','Amareleja'),
            ('7860-45','Rua do Escalatrim','Beja','Moura','Moura'),
            ('7875-170','Rua de Santo António','Beja','Moura','Santo Aleixo da Restauração'),
            ('7630-141','Praça José Maria Lopes Falcão','Beja','Odemira','Odemira'),
            ('7645-278','Rua Doutor Manuel Joaquim Águas','Beja','Odemira','Vila Nova de Milfontes'),
            ('7670-133','Rua das Amoreiras','Beja','Ourique','Garvão'),
            ('7830-274','Travessa do Passeio','Beja','Serpa','Pias'),
            ('7830-521','Rua General Humberto Delgado','Beja','Serpa','Vale de Vargo'),
            ('7960-168','Rua das Figueiras','Beja','Vidigueira','Selmes'),
            ('4720-789','Rua do Bairro Municipal','Braga','Amares','Amares'),
            ('4720-119','Rua do Rio Homem','Braga','Amares','Rendufe'),
            ('4720-59','Rua dos Burgos','Braga','Amares','Prozelo'),
            ('4720-417','Rua Nossa Senhora da Conceição','Braga','Amares','Figueiredo'),
            ('4720-667','Rua da Igreja','Braga','Amares','Bouro de Santa Marta'),
            ('4720-282','Rua de Barriomau','Braga','Amares','Carrazedo'),
            ('4905-42','Travessa da Regueira','Braga','Barcelos','Balugães'),
            ('4755-17','Rua de Feital','Braga','Barcelos','Alvelos'),
            ('4775-263','Rua de Nossa Senhora da Apresentação','Braga','Barcelos','Viatodos'),
            ('4755-210','Rua da Capela','Braga','Barcelos','Fornelos'),
            ('4750-86','Rua do Sobral','Braga','Barcelos','Alvito de São Pedro'),
            ('4755-203','Rua do Olival','Braga','Barcelos','Faria'),
            ('4775-161','Rua da Torre','Braga','Barcelos','Minhotães'),
            ('4750-704','Travessa do Machado','Braga','Barcelos','Tamel'),
            ('4775-170','Rua da Bouça Nova','Braga','Barcelos','Monte de Fralães'),
            ('4755-608','Rua do Reborido','Braga','Barcelos','Gamil'),
            ('4750-379','Largo do Carvalho Santo','Braga','Barcelos','Carapeços'),
            ('4755-257','Rua de Medros','Braga','Barcelos','Carvalhal'),
            ('4905-117','Rua da Mourinha','Braga','Barcelos','Fragoso'),
            ('4750-364','Rua de Merouces','Braga','Barcelos','Campo'),
            ('4775-39','Travessa da Fonte Susa','Braga','Barcelos','Cambeses'),
            ('4905-164','Rua de Pedrosas','Braga','Barcelos','Tregosa'),
            ('4750-482','Rua de Santa Marinha','Braga','Barcelos','Galegos (São Martinho) '),
            ('4755-359','Rua de Real','Braga','Barcelos','Moure'),
            ('4750-13','Rua da Estrada Velha','Braga','Barcelos','Abade de Neiva'),
            ('4750-79','Rua das Irmãs Franciscanas Missionárias de Maria','Braga','Barcelos','Barcelos'),
            ('4750-312','Avenida da Liberdade','Braga','Barcelos','Barcelos'),
            ('4755-269','Rua Monte do Picoto','Braga','Barcelos','Macieira de Rates'),
            ('4755-556','Rua da Poça da Lage','Braga','Barcelos','Vila Seca'),
            ('4705-509','Rua Nova da Naia','Braga','Braga','Morreira'),
            ('4710-585','Rua de Penela','Braga','Braga','Adaúfe'),
            ('4715-456','Rua de Bugide','Braga','Braga','Pedralva'),
            ('4715-648','Rua do Centro Social','Braga','Braga','Sobreposta'),
            ('4710-912','Rua da Cal','Braga','Braga','Crespos'),
            ('4705-70','Rua Senhora do Parto','Braga','Braga','Aveleda'),
            ('4710-103','Rua José Sarmento','Braga','Braga','Braga'),
            ('4704-533','Praça Doutor José Augusto Ferreira Salgado','Braga','Braga','Braga'),
            ('4715-212','Rua do Nogueirense','Braga','Braga','Braga'),
            ('4700-238','Rua Padre Martinho da Silva Penedo','Braga','Braga','Braga'),
            ('4700-228','Rua Madre de Deus','Braga','Braga','Braga'),
            ('4705-112','Rua da Ventosa','Braga','Braga','Braga'),
            ('4715-354','Caminho do Espinho','Braga','Braga','Braga'),
            ('4705-86','Rua Cidade do Porto','Braga','Braga','Braga'),
            ('4700-682','Rua Assento de Cima','Braga','Braga','Palmeira'),
            ('4860-72','Rua da Cerâmica','Braga','Cabeceiras de Basto','Arco de Baúlhe'),
            ('4740-10','Rua da Fábrica','Braga','Esposende','Esposende'),
            ('4740-275','Rua José Vieira','Braga','Esposende','Esposende'),
            ('4740-397','Travessa Prior António Nogueira','Braga','Esposende','Fão'),
            ('4740-612','Rua de Cervães','Braga','Esposende','Rio Tinto'),
            ('4820-65','Rua da Capela','Braga','Fafe','Estorãos'),
            ('4820-228','Rua do Calças','Braga','Fafe','Fafe'),
            ('4820-616','Rua de São José','Braga','Fafe','Regadas'),
            ('4820-752','Rua da Prelada','Braga','Fafe','Arões ( São Romão)'),
            ('4820-652','Rua do Monte','Braga','Fafe','São Gens'),
            ('4800-234','Travessa da Cancela','Braga','Guimarães','Atães'),
            ('4805-134','Rua do Monte Jafonsa','Braga','Guimarães','Caldas das Taipas'),
            ('4765-450','Rua Pedrais de Cima','Braga','Guimarães','Guardizela'),
            ('4835-403','Travessa da Agrela','Braga','Guimarães','Guimarães'),
            ('4810-554','Travessa de Arcela','Braga','Guimarães','Guimarães'),
            ('4810-557','Rua das Vessadas','Braga','Guimarães','Guimarães'),
            ('4800-54','Travessa dos Martires','Braga','Guimarães','Guimarães'),
            ('4835-54','Rua Gil Eanes','Braga','Guimarães','Guimarães'),
            ('4805-659','Rua da Escola','Braga','Guimarães','Leitões'),
            ('4815-322','Rua Domingos Costa Abreu','Braga','Guimarães','Moreira de Cónegos'),
            ('4805-233','Rua do Campo Novo','Braga','Guimarães','Ponte'),
            ('4805-448','Rua São Romão','Braga','Guimarães','Briteiros São Salvador'),
            ('4805-531','Rua Monte','Braga','Guimarães','Sande São Martinho'),
            ('4765-572','Travessa de Pedrados','Braga','Guimarães','Serzedelo'),
            ('4805-491','Rua Nossa Senhora da Saúde','Braga','Guimarães','São Clemente de Sande'),
            ('4810-714','Travessa Cabo de Vila','Braga','Guimarães','Abação de São Tomé'),
            ('4810-575','Rua Nossa Senhora de Fátima','Braga','Guimarães','Infantas'),
            ('4830-65','Rua de Calvos','Braga','Póvoa de Lanhoso','Calvos'),
            ('4830-583','Caminho da Moleira','Braga','Póvoa de Lanhoso','Póvoa de Lanhoso'),
            ('4830-345','Rua 10 de Março','Braga','Póvoa de Lanhoso','Fontarcada'),
            ('4830-380','Rua Sobrado de Cima','Braga','Póvoa de Lanhoso','Louredo'),
            ('4830-331','Rua do Polidesportivo','Braga','Póvoa de Lanhoso','Lanhoso'),
            ('4830-827','Travessa de Santa Catarina','Braga','Póvoa de Lanhoso','Vilela'),
            ('4830-407','Travessa da Mó','Braga','Póvoa de Lanhoso','Monsul'),
            ('4850-144','Rua Pedra Chã','Braga','Vieira do Minho','Eira Vedra'),
            ('4765-67','Travessa Fonte da Arcada','Braga','Vila Nova de Famalicão','Bairro'),
            ('4760-501','Rua do Alto da Vela','Braga','Vila Nova de Famalicão','Gondifelos'),
            ('4760-583','Travessa Sovais','Braga','Vila Nova de Famalicão','Louro'),
            ('4770-451','Rua Nuno Dias Mendes','Braga','Vila Nova de Famalicão','Requião'),
            ('4760-710','Travessa dos Artesãos','Braga','Vila Nova de Famalicão','Ribeirão'),
            ('4770-648','Travessa Além de Baixo','Braga','Vila Nova de Famalicão','São Miguel Seide'),
            ('4760-287','Praceta da Liberdade','Braga','Vila Nova de Famalicão','Vila Nova de Famalicão'),
            ('4760-694','Rua Dom Jorge Ferreira Costa Ortiga','Braga','Vila Nova de Famalicão','Vila Nova de Famalicão'),
            ('4770-144','Rua de Viadeiros','Braga','Vila Nova de Famalicão','Cruz'),
            ('4760-480','Travessa Dom Nuno Álvares Pereira','Braga','Vila Nova de Famalicão','Esmeriz'),
            ('4770-11','Rua Camilo Castelo Branco','Braga','Vila Nova de Famalicão','Abade de Vermoim'),
            ('4770-573','Rua de Lamela','Braga','Vila Nova de Famalicão','Vale de São Cosme'),
            ('4770-755','Rua de Além','Braga','Vila Nova de Famalicão','Vermoim'),
            ('4775-487','Rua do Este','Braga','Vila Nova de Famalicão','Santa Eulália de Arnoso'),
            ('4770-282','Viela do Fontanário','Braga','Vila Nova de Famalicão','Lagoa'),
            ('4765-601','Rua D\'Abade','Braga','Vila Nova de Famalicão','Delães'),
            ('4770-482','Rua da Boavista','Braga','Vila Nova de Famalicão','Ruivães'),
            ('4730-68','Rua das Flores','Braga','Vila Verde','Barbudo'),
            ('4730-467','Rua 2','Braga','Vila Verde','Vila de Prado'),
            ('4730-260','Rua Padre António José de Araújo','Braga','Vila Verde','Lanhas'),
            ('4730-300','Travessa 1 da Landeira','Braga','Vila Verde','Moure'),
            ('4730-281','Travessa do Ouroso','Braga','Vila Verde','Marrancos'),
            ('4815-396','Rua Agostinho de Lima','Braga','Vizela','Vizela'),
            ('4815-385','Rua das Quintãs','Braga','Vizela','Ínfias'),
            ('4620-520','Ruela do Alto de Silvares','Braga','Vizela','Santa Eulália'),
            ('5300-42','Rua do Pontão','Bragança','Bragança','Bragança'),
            ('5300-466','Travessa da Coxa','Bragança','Bragança','Bragança'),
            ('5300-855','Quinta do Seixo','Bragança','Bragança','Samil'),
            ('5180-120','Largo do Terreirinho','Bragança','Freixo de Espada à Cinta','Freixo de Espada à Cinta'),
            ('5340-340','Rua Manuel Cardoso','Bragança','Macedo de Cavaleiros','Macedo de Cavaleiros'),
            ('5210-191','Largo General Humberto Delgado','Bragança','Miranda do Douro','Miranda do Douro'),
            ('5370-422','Rua dos Távoras','Bragança','Mirandela','Mirandela'),
            ('5200-238','Rua das Fragas','Bragança','Mogadouro','Mogadouro'),
            ('5160-134','Rua da Mina','Bragança','Torre de Moncorvo','Lousa'),
            ('5360-999','Rua Doutor Eduardo Cabral','Bragança','Vila Flor','Vila Flor'),
            ('5230-317','Rua Conselheiro José Alpoim','Bragança','Vimioso','Vimioso'),
            ('6250-60','Rua Gago Coutinho e Sacadura Cabral','Castelo Branco','Belmonte','Belmonte'),
            ('6005-97','Rua Tecelões','Castelo Branco','Castelo Branco','Alcains'),
            ('6000-790','Rua T 1','Castelo Branco','Castelo Branco','Castelo Branco'),
            ('6000-779','Itinerário Principal 2','Castelo Branco','Castelo Branco','Castelo Branco'),
            ('6225-137','Travessa de Santo António','Castelo Branco','Covilhã','Casegas'),
            ('6200-24','Beco da Rua das Túlipas','Castelo Branco','Covilhã','Covilhã'),
            ('6200-432','Travessa Pedreira','Castelo Branco','Covilhã','Covilhã'),
            ('6200-240','Rua Tapada','Castelo Branco','Covilhã','Covilhã'),
            ('6200-591','Rua dos Salgueirinhos','Castelo Branco','Covilhã','Peraboa'),
            ('6200-788','Ponte Pedrinha','Castelo Branco','Covilhã','Tortosendo'),
            ('6200-801','Rua Outeiro','Castelo Branco','Covilhã','Vale Formoso'),
            ('6230-69','Terreiro de Santo António','Castelo Branco','Fundão','Alpedrinha'),
            ('6230-473','Quinta do Olival Grande','Castelo Branco','Fundão','Fundão'),
            ('6060-11','Rua do Forno','Castelo Branco','Idanha-a-Nova','Alcafozes'),
            ('6060-91','Rua Marquês da Graciosa','Castelo Branco','Idanha-a-Nova','Monsanto'),
            ('6060-539','Rua Fonte de Baixo','Castelo Branco','Idanha-a-Nova','Zebreira'),
            ('6185-270','Rua Padre Domingos Vaz Azevedo','Castelo Branco','Oleiros','Orvalho'),
            ('6090-274','Largo do Terreiro','Castelo Branco','Penamacor','Bemposta'),
            ('6090-558','Rua de São Domingos','Castelo Branco','Penamacor','Penamacor'),
            ('6150-542','Rua da Fonte Velha','Castelo Branco','Proença-a-Nova','Proença-a-Nova'),
            ('3300-62','Rua Oliveira Matos','Coimbra','Arganil','Arganil'),
            ('3060-38','Rua de São Sebastião','Coimbra','Cantanhede','Ançã'),
            ('3060-543','Rua da Gesteira','Coimbra','Cantanhede','Sepins'),
            ('3040-657','Rua do Ribeirinho','Coimbra','Coimbra','Assafarge'),
            ('3040-771','Rua 1º de Maio','Coimbra','Coimbra','Cernache'),
            ('3030-996','Rua Doutor Paulo Quintela','Coimbra','Coimbra','Coimbra'),
            ('3000-372','Largo de São Salvador','Coimbra','Coimbra','Coimbra'),
            ('3000-446','Urbanização Panorama','Coimbra','Coimbra','Coimbra'),
            ('3020-308','Largo da Rocha Nova','Coimbra','Coimbra','Coimbra'),
            ('3000-112','Rua Cidade de Santos','Coimbra','Coimbra','Coimbra'),
            ('3040-207','Rua do Alto da Cioga','Coimbra','Coimbra','Coimbra'),
            ('3040-197','Travessa Central da Mesura','Coimbra','Coimbra','Coimbra'),
            ('3025-278','Rua 25 de Abril','Coimbra','Coimbra','Coimbra'),
            ('3020-87','Rua da Juventude','Coimbra','Coimbra','Coimbra'),
            ('3020-491','Rua do Passadiço','Coimbra','Coimbra','Coimbra'),
            ('3025-378','Estrada Nacional 576','Coimbra','Coimbra','Casal das Figueiras'),
            ('3025-524','Rua da Escola','Coimbra','Coimbra','Quimbres'),
            ('3020-854','Beco das Eiras','Coimbra','Coimbra','Souselas'),
            ('3090-406','Rua da Cavada','Coimbra','Figueira da Foz','Broeiras'),
            ('3090-661','Parque Campismo Cabedelo','Coimbra','Figueira da Foz','Cabedelo'),
            ('3080-39','Praça Doutor Francisco Lopes Guimarães','Coimbra','Figueira da Foz','Figueira da Foz'),
            ('3090-724','Rua das Artes','Coimbra','Figueira da Foz','Gala'),
            ('3090-485','Rua dos Lagoeiros','Coimbra','Figueira da Foz','Marinha das Ondas'),
            ('3080-744','Rua da Figueira da Foz','Coimbra','Figueira da Foz','Cova da Serpe'),
            ('3070-49','Rua do Tanoeiro','Coimbra','Mira','Casal de São Tomé'),
            ('3070-376','Travessa do X','Coimbra','Mira','Portomar'),
            ('3070-535','Rua dos Cabaços','Coimbra','Mira','Seixo'),
            ('3140-615','Rua do Balcão','Coimbra','Montemor-o-Velho','Verride'),
            ('3405-15','Rua Emília Pestana Coelho','Coimbra','Oliveira do Hospital','Bobadela'),
            ('3405-254','Quinta da Urtigueira','Coimbra','Oliveira do Hospital','Lagos da Beira'),
            ('3400-481','Rua do Pelourinho','Coimbra','Oliveira do Hospital','Nogueira do Cravo'),
            ('3400-574','Quinta dos Linhares','Coimbra','Oliveira do Hospital','Penalva de Alva'),
            ('3405-406','Rua da Lage','Coimbra','Oliveira do Hospital','Seixas'),
            ('3230-249','Rua da Fopa','Coimbra','Penela','Penela'),
            ('7250-121','Rua da Eiras do Ravasco','Évora','Alandroal','Alandroal'),
            ('7040-219','Rua das Casas Novas','Évora','Arraiolos','Igrejinha'),
            ('7150-250','Praceta José Régio','Évora','Borba','Borba'),
            ('7150-378','Rua Mestre António Talhinhos','Évora','Borba','Rio de Moinhos'),
            ('7000-616','Travessa do Baldaia','Évora','Évora','Évora'),
            ('7005-657','Travessa das Nogueiras','Évora','Évora','Évora'),
            ('7000-741','Avenida Batalha do Salado','Évora','Évora','Évora'),
            ('7005-198','Quinta do Bacelo','Évora','Évora','Évora'),
            ('7005-626','Rua Sózinha','Évora','Évora','Évora'),
            ('7200-42','Praça 1º de Maio','Évora','Évora','Vendinha'),
            ('7050-99','Avenida Gago Coutinho','Évora','Montemor-o-Novo','Montemor-O-Novo'),
            ('7050-206','Rua de São Sebastião','Évora','Montemor-o-Novo','São Geraldo'),
            ('7490-403','Bairro Pedro Manuel','Évora','Mora','Pavia'),
            ('7220-301','Rua do Poço','Évora','Portel','Oriola'),
            ('7170-34','Rua Estrada dos Foros','Évora','Redondo','Redondo'),
            ('7200-469','Rua do Ferrador','Évora','Reguengos de Monsaraz','Perolivas'),
            ('2965-417','Rua Paz','Évora','Vendas Novas','Landeira'),
            ('7080-101','Avenida da República','Évora','Vendas Novas','Vendas Novas'),
            ('7090-289','Travessa da Lindinha','Évora','Viana do Alentejo','Viana do Alentejo'),
            ('7160-250','Rua Combatentes da Grande Guerra','Évora','Vila Viçosa','Vila Viçosa'),
            ('8200-129','Rua Fernão Magalhães','Faro','Albufeira','Albufeira'),
            ('8200-227','Rua D','Faro','Albufeira','Albufeira'),
            ('8970-371','Rua do Carmo','Faro','Alcoutim','Vaqueiros'),
            ('8670-430','Rua da Escola','Faro','Aljezur','Maria Vinagre'),
            ('8950-282','Urbanização Quinta da Cerca','Faro','Castro Marim','Castro Marim'),
            ('8000-502','Bairro da Horta da Areia','Faro','Faro','Faro'),
            ('8000-369','Rua João Dias','Faro','Faro','Faro'),
            ('8000-324','Rua Doutor Emiliano da Costa','Faro','Faro','Faro'),
            ('8005-547','Travessa Doutor José Domingos Garcia Domingues','Faro','Faro','Faro'),
            ('8005-201','Rua das Violetas','Faro','Faro','Gambelas'),
            ('8400-252','Rua Infante Santo','Faro','Lagoa (Algarve)','Ferragudo'),
            ('8400-655','Urbanização das Marinhas','Faro','Lagoa (Algarve)','Parchal'),
            ('8600-512','Estrada da Ponta da Piedade','Faro','Lagos','Lagos'),
            ('8600-325','Travessa da Igreja','Faro','Lagos','Lagos'),
            ('8600-358','Rua Rosa Pacheco da Cruz','Faro','Lagos','Lagos'),
            ('8600-212','Rua dos Pintassilgos','Faro','Lagos','Luz'),
            ('8135-34','Travessa da Laranjeira','Faro','Loulé','Almancil'),
            ('8100-70','Rua São Sebastião','Faro','Loulé','Boliqueime'),
            ('8100-678','Rua Brites de Almeida','Faro','Loulé','Loulé'),
            ('8100-614','Rua Poeta Aleixo','Faro','Loulé','Loulé'),
            ('8125-254','Rua São Tomé e Principe','Faro','Loulé','Quarteira'),
            ('8100-381','Rua dos Arneiros','Faro','Loulé','Aldeia de Tor'),
            ('8125-582','Volta da Proa','Faro','Loulé','Vilamoura'),
            ('8700-491','Rua do Caminho de Ferro','Faro','Olhão','Olhão'),
            ('8500-34','Beco Raul de Alvor','Faro','Portimão','Alvor'),
            ('8500-321','Rua da Alvorada','Faro','Portimão','Portimão'),
            ('8500-607','Rua Dom Carlos I','Faro','Portimão','Portimão'),
            ('8500-699','Rua João de Deus','Faro','Portimão','Portimão'),
            ('8500-515','Rua D da Urbanização Quinta do Caneco','Faro','Portimão','Portimão'),
            ('8365-26','Rua dos Espinhos','Faro','Silves','Alcantarilha'),
            ('8300-135','Rua Projectada à Rua Diogo Manuel','Faro','Silves','Silves'),
            ('8800-82','Rua Comendador Domingos de Sousa Uva','Faro','Tavira','Conceição'),
            ('8800-608','Rua Fernão Magalhães','Faro','Tavira','Tavira'),
            ('8650-103','Beco do Saco','Faro','Vila do Bispo','Burgau'),
            ('8900-412','Avenida Infante Dom Henrique','Faro','Vila Real de Santo António','Monte Gordo'),
            ('8900-65','Rua da Orlamar','Faro','Vila Real de Santo António','Vila Nova de Cacela'),
            ('8900-228','Estrada Nacional 122','Faro','Vila Real de Santo António','Vila Real de Santo António'),
            ('6355-282','Rua São João','Guarda','Almeida','Vilar Formoso'),
            ('6360-519','Travessa da Rua das Videiras','Guarda','Celorico da Beira','Lajeosa do Mondego'),
            ('6370-0','Urbanização Zona Sul','Guarda','Fornos de Algodres','Fornos de Algodres'),
            ('6290-366','Rua Miguel Torga','Guarda','Gouveia','Gouveia'),
            ('6300-713','Rua General Pinto Monteiro','Guarda','Guarda','Guarda'),
            ('6300-306','Rua de Acesso à Avenida dos Bombeiros Voluntários Egitanienses','Guarda','Guarda','Guarda'),
            ('6430-153','Rua Cabeço','Guarda','Meda','Meda'),
            ('6400-411','Rua Maria do Céu Bandarra','Guarda','Pinhel','Pinhel'),
            ('6320-333','Largo de São Pedro','Guarda','Sabugal','Sabugal'),
            ('6270-95','Rua de São Bento','Guarda','Seia','Loriga'),
            ('6270-492','Largo de Santa Rita','Guarda','Seia','Seia'),
            ('6285-118','Rua da Venda','Guarda','Seia','Vide'),
            ('6420-15','Largo Dom Afonso Henriques','Guarda','Trancoso','Trancoso'),
            ('5150-78','Quelha Serrana','Guarda','Vila Nova de Foz Côa','Almendra'),
            ('5155-244','Rua Engenheiro Pais Clemente','Guarda','Vila Nova de Foz Côa','Freixo de Numão'),
            ('5155-652','Quelha Padres António e João Almeida','Guarda','Vila Nova de Foz Côa','Santo Amaro'),
            ('5150-644','Estrada Nacional 102','Guarda','Vila Nova de Foz Côa','Vila Nova de Foz Côa'),
            ('2460-492','Rua Nova','Leiria','Alcobaça','Évora'),
            ('2460-603','Rua das Mós','Leiria','Alcobaça','Boavista'),
            ('2445-42','Beco do Rodrigues','Leiria','Alcobaça','Burinhosa'),
            ('2445-353','Rua Mato Pinheiro','Leiria','Alcobaça','Pataias'),
            ('3240-123','Rua Salgueiro','Leiria','Ansião','Ansião'),
            ('2440-486','Rua da Poesia','Leiria','Batalha','Casal do Relvas'),
            ('2540-338','Travessa Nossa Senhora do Socorro','Leiria','Bombarral','Carvalhal'),
            ('2540-600','Rua Francisco Mega','Leiria','Bombarral','Columbeira'),
            ('2500-938','Estrada Nacional 114','Leiria','Caldas da Rainha','Caldas da Rainha'),
            ('2500-192','Rua Doutor Júlio Lopes','Leiria','Caldas da Rainha','Caldas da Rainha'),
            ('2500-506','Rua Professora Júlia Nogueira','Leiria','Caldas da Rainha','Foz do Arelho'),
            ('2500-667','Rua 1º de Maio','Leiria','Caldas da Rainha','Salir do Porto'),
            ('3280-40','Rua Eduardo Silva','Leiria','Castanheira de Pêra','Castanheira de Pêra'),
            ('2425-426','Rua do Barreiro','Leiria','Leiria','Carvide'),
            ('2420-211','Avenida da Victória','Leiria','Leiria','Lagares'),
            ('2415-577','Rua Dona Glória Barata Rodrigues','Leiria','Leiria','Leiria'),
            ('2415-371','Rua Anzebino da Cruz Saraiva','Leiria','Leiria','Leiria'),
            ('2410-161','Rua da Restauração','Leiria','Leiria','Leiria'),
            ('2400-115','Travessa do Castelo','Leiria','Leiria','Leiria'),
            ('2400-504','Estrada Nacional 1','Leiria','Leiria','Leiria'),
            ('2415-467','Rua Sapateira','Leiria','Leiria','Leiria'),
            ('2410-145','Rua Doutor Paulino da Costa Santos','Leiria','Leiria','Leiria'),
            ('2400-122','Avenida dos Combatentes da Grande Guerra','Leiria','Leiria','Leiria'),
            ('2425-101','Rua da Tabaneta','Leiria','Leiria','Granja'),
            ('2425-730','Rua da Serrada','Leiria','Leiria','Monte Agudo'),
            ('2495-162','Travessa da Barrada','Leiria','Leiria','Loureira'),
            ('2425-504','Estrada Nacional 109','Leiria','Leiria','Arroteia'),
            ('2410-493','Rua Barreira de Meda','Leiria','Leiria','Telheiro'),
            ('2430-180','Travessa Corgo do Sul','Leiria','Marinha Grande','Comeira'),
            ('2430-174','Avenida Vitor Gallo','Leiria','Marinha Grande','Marinha Grande'),
            ('2430-322','Rua Gregório Silva','Leiria','Marinha Grande','Pilado'),
            ('2430-596','Travessa dos Pedrosas','Leiria','Marinha Grande','Vieira de Leiria'),
            ('2450-146','Largo Pinta','Leiria','Nazaré','Nazaré'),
            ('2450-65','Beco do Semião','Leiria','Nazaré','Sítio da Nazaré'),
            ('2510-479','Rua do Vale Verde','Leiria','Óbidos','Amoreira'),
            ('2510-103','Largo Serra','Leiria','Óbidos','Óbidos'),
            ('3270-173','Rua do Meio','Leiria','Pedrógão Grande','Pedrógão Grande'),
            ('2525-176','Rua do Carreirinho','Leiria','Peniche','Bufarda'),
            ('2525-512','Largo de São Sebastião','Leiria','Peniche','Geraldes'),
            ('2520-104','Largo de Nossa Senhora da Guia','Leiria','Peniche','Ferrel'),
            ('2520-626','Bairro do Calvário','Leiria','Peniche','Peniche'),
            ('2520-437','Rua Filipa de Vilhena','Leiria','Peniche','Peniche'),
            ('2480-389','Rua da Fonte','Leiria','Porto de Mós','Juncal'),
            ('2485-104','Rua da Paz','Leiria','Porto de Mós','Mira de Aire'),
            ('2580-101','Rua Conde Temude','Lisboa','Alenquer','Aldeia Gavinha'),
            ('2580-358','Travessa da Ermida','Lisboa','Alenquer','Alenquer'),
            ('2580-470','Rua Castelo Melhor','Lisboa','Alenquer','Carregado'),
            ('2630-143','Casal Lages','Lisboa','Arruda dos Vinhos','Arruda dos Vinhos'),
            ('2630-423','Casal Sol','Lisboa','Arruda dos Vinhos','Cardosas'),
            ('2065-127','Travessa da Escola','Lisboa','Azambuja','Alcoentre'),
            ('2050-40','Rua Francisco Vitorino dos Santos','Lisboa','Azambuja','Aveiras de Baixo'),
            ('2050-198','Travessa da Caneira','Lisboa','Azambuja','Aveiras de Cima'),
            ('2050-356','Beco da Rua Direita','Lisboa','Azambuja','Azambuja'),
            ('2050-447','Rua de Pancas','Lisboa','Azambuja','Vale do Paraiso'),
            ('2550-69','Rua da Charneca','Lisboa','Cadaval','Vilar'),
            ('2755-91','Rua dos Lírios','Lisboa','Cascais','Alcabideche'),
            ('2645-131','Estrada de Manique','Lisboa','Cascais','Alcoitão'),
            ('2645-371','Rua do Cabeço','Lisboa','Cascais','Bicesse'),
            ('2755-81','Praceta Vitória Correia Venâncio','Lisboa','Cascais','Malveira da Serra'),
            ('2785-288','Largo Jardim de São Pedro','Lisboa','Cascais','Arneiro'),
            ('2775-667','Escadinhas do Mercado','Lisboa','Cascais','Alto dos Lombos'),
            ('2750-12','Rua Fernando Pessoa','Lisboa','Cascais','Aldeia de Juzo'),
            ('2750-181','Avenida de Nossa Senhora do Rosário','Lisboa','Cascais','Cascais'),
            ('2750-175','Rua João de Santarém','Lisboa','Cascais','Cascais'),
            ('2754-527','Avenida de Dom Pedro i','Lisboa','Cascais','Cascais'),
            ('2750-7','Rua das Piscinas','Lisboa','Cascais','Quinta da Marinha'),
            ('2765-467','Estrada das Areias','Lisboa','Cascais','Areias'),
            ('2750-718','Rua de Santo António','Lisboa','Cascais','Monte Estoril'),
            ('2775-364','Avenida Marginal','Lisboa','Cascais','Parede'),
            ('2775-271','Avenida da República','Lisboa','Cascais','Parede'),
            ('2785-114','Rua Principal','Lisboa','Cascais','Cabeço de Mouro'),
            ('2785-453','Rua Gaspar Corte Real','Lisboa','Cascais','Matarraque'),
            ('2785-733','Rua de Crasso','Lisboa','Cascais','Talaíde'),
            ('2785-69','Rua Dom Pedro V','Lisboa','Cascais','Tires'),
            ('2775-22','Rua Claudina Chamiço','Lisboa','Cascais','Junqueiro'),
            ('1200-106','Rua das Chagas','Lisboa','Lisboa','Lisboa'),
            ('1800-110','Rua Cidade de Novo Redondo','Lisboa','Lisboa','Lisboa'),
            ('1350-82','Casal Colares','Lisboa','Lisboa','Lisboa'),
            ('1749-58','Rua Coronel Bento Roma','Lisboa','Lisboa','Lisboa'),
            ('1170-109','Rua Damasceno Monteiro','Lisboa','Lisboa','Lisboa'),
            ('1070-82','Rua Dom Carlos de Mascarenhas','Lisboa','Lisboa','Lisboa'),
            ('1950-80','Avenida Doutor Arlindo Vicente','Lisboa','Lisboa','Lisboa'),
            ('1069-152','Avenida Duque de Loulé','Lisboa','Lisboa','Lisboa'),
            ('1050-105','Rua Engenheiro Vieira da Silva','Lisboa','Lisboa','Lisboa'),
            ('1300-230','Rua Feliciano de Sousa','Lisboa','Lisboa','Lisboa'),
            ('1300-251','Travessa das Florindas','Lisboa','Lisboa','Lisboa'),
            ('1950-138','Rua da Fraternidade Operária','Lisboa','Lisboa','Lisboa'),
            ('1649-43','Rua General Firmino Miguel','Lisboa','Lisboa','Lisboa'),
            ('1700-94','Campo Grande','Lisboa','Lisboa','Lisboa'),
            ('1100-21','Beco do Almotacé','Lisboa','Lisboa','Lisboa'),
            ('1169-45','Rua Jacinta Marto','Lisboa','Lisboa','Lisboa'),
            ('1950-157','Avenida João Paulo II','Lisboa','Lisboa','Lisboa'),
            ('1150-201','Rua José Estêvão','Lisboa','Lisboa','Lisboa'),
            ('1000-34','Rua Alves Torgo','Lisboa','Lisboa','Lisboa'),
            ('1950-179','Rua Luís Cristino da Silva','Lisboa','Lisboa','Lisboa'),
            ('1150-219','Rua Manuel Bento de Sousa','Lisboa','Lisboa','Lisboa'),
            ('1990-97','Avenida Dom João II','Lisboa','Lisboa','Lisboa'),
            ('1990-162','Rua de Moscavide','Lisboa','Lisboa','Lisboa'),
            ('1990-203','Alameda dos Oceanos','Lisboa','Lisboa','Lisboa'),
            ('1990-243','Travessa do Sandokan','Lisboa','Lisboa','Lisboa'),
            ('1750-399','Avenida Glicínia Quartin','Lisboa','Lisboa','Lisboa'),
            ('1900-325','Rua Margem','Lisboa','Lisboa','Lisboa'),
            ('1950-201','Rua de Marvila','Lisboa','Lisboa','Lisboa'),
            ('1700-307','Rua Moura Girão','Lisboa','Lisboa','Lisboa'),
            ('1170-17','Rua Angelina Vidal','Lisboa','Lisboa','Lisboa'),
            ('1150-251','Travessa das Parreiras','Lisboa','Lisboa','Lisboa'),
            ('1050-171','Rua Pedro Nunes','Lisboa','Lisboa','Lisboa'),
            ('1600-584','Estrada da Pontinha','Lisboa','Lisboa','Lisboa'),
            ('1500-493','Rua E do Loteamento do Alto dos Moinhos','Lisboa','Lisboa','Lisboa'),
            ('1800-323','Rua Quinta do Morgado','Lisboa','Lisboa','Lisboa'),
            ('1200-378','Beco Ricarda','Lisboa','Lisboa','Lisboa'),
            ('1950-253','Rua Rui de Sousa','Lisboa','Lisboa','Lisboa'),
            ('1100-495','Calçada de Santo André','Lisboa','Lisboa','Lisboa'),
            ('1200-849','Rua de São João da Mata','Lisboa','Lisboa','Lisboa'),
            ('1170-359','Rua Senhora do Monte','Lisboa','Lisboa','Lisboa'),
            ('1099-72','Rua Artilharia 1','Lisboa','Lisboa','Lisboa'),
            ('1200-468','Rua da Trindade','Lisboa','Lisboa','Lisboa'),
            ('1800-362','Rua 25','Lisboa','Lisboa','Lisboa'),
            ('1100-60','Rua Áurea','Lisboa','Lisboa','Lisboa'),
            ('1150-60','Rua das Barracas','Lisboa','Lisboa','Lisboa'),
            ('1150-71','Rua Bernardim Ribeiro','Lisboa','Lisboa','Lisboa'),
            ('1750-194','Estrada Militar','Lisboa','Lisboa','Lisboa'),
            ('1169-128','Rua Camilo Castelo Branco','Lisboa','Lisboa','Lisboa'),
            ('1350-68','Rua Carlos da Maia','Lisboa','Lisboa','Lisboa'),
            ('1900-882','Rua Almirante Sarmento Rodrigues','Lisboa','Lisboa','Lisboa'),
            ('2695-506','Rua dos Narcisos','Lisboa','Loures','Bobadela'),
            ('2680-151','Travessa das Mós','Lisboa','Loures','Camarate'),
            ('2680-34','Travessa Bento Gonçalves','Lisboa','Loures','Camarate'),
            ('2670-710','Travessa da Cruz','Lisboa','Loures','Fanhões'),
            ('2670-464','Rua Ponta Delgada','Lisboa','Loures','Loures'),
            ('2670-491','Rua da Calheta','Lisboa','Loures','Loures'),
            ('1990-375','Rua Robinson Crusoé','Lisboa','Loures','Moscavide'),
            ('2685-356','Beco da Rua Principal','Lisboa','Loures','Prior Velho'),
            ('2685-75','Rua José Luís de Morais','Lisboa','Loures','Sacavém'),
            ('2685-28','Rua Barbosa Du Bocage','Lisboa','Loures','Sacavém'),
            ('2690-236','Rua do Universo','Lisboa','Loures','Santa Iria de Azóia'),
            ('2690-299','Avenida 11 de Março','Lisboa','Loures','Santa Iria de Azóia'),
            ('2660-149','Rua das Hortenses','Lisboa','Loures','Santo Antão do Tojal'),
            ('2695-500','Rua do Mercado','Lisboa','Loures','São João da Talha'),
            ('2695-722','Rua Deputado Pedro Botelho Neves','Lisboa','Loures','São João da Talha'),
            ('2695-534','Rua do Brasil','Lisboa','Loures','São João da Talha'),
            ('2660-385','Rua Bento Gonçalves','Lisboa','Loures','São Julião do Tojal'),
            ('2660-315','Rua de Nossa Senhora da Nazaré','Lisboa','Loures','Santo António dos Cavaleiros'),
            ('2530-904','Rua Nascer do Sol','Lisboa','Lourinhã','Atalaia'),
            ('2530-911','Estrada Municipal 571','Lisboa','Lourinhã','Lourinhã'),
            ('2530-311','Rua da Escola','Lisboa','Lourinhã','Sobral'),
            ('2530-435','Travessa do Poçinho','Lisboa','Lourinhã','Miragaia'),
            ('2530-514','Estrada da Confraria','Lisboa','Lourinhã','Moledo'),
            ('2530-676','Travessa da Atlântica','Lisboa','Lourinhã','Ribamar'),
            ('2530-790','Travessa dos Silvas','Lisboa','Lourinhã','Toledo'),
            ('2655-35','Praceta Cruz da Baleia','Lisboa','Mafra','Baleia'),
            ('2640-121','Rua do Arco da Ponte','Lisboa','Mafra','Cheleiros'),
            ('2640-254','Praceta Mar e Sol','Lisboa','Mafra','Encarnação'),
            ('2655-232','Rua do Arrabalde','Lisboa','Mafra','Ericeira'),
            ('2655-441','Rua Casal das Magras','Lisboa','Mafra','Ericeira'),
            ('2665-112','Rua dos Correios','Lisboa','Mafra','Gradil'),
            ('2640-817','Rua das Olarias','Lisboa','Mafra','Mafra'),
            ('2665-271','Travessa Vicente Franco','Lisboa','Mafra','Malveira'),
            ('2665-505','Rua do Planalto','Lisboa','Mafra','Venda do Pinheiro'),
            ('2665-425','Rua de Nossa Senhora do Rosário','Lisboa','Mafra','Vila Franca do Rosário'),
            ('1495-117','Estrada das Romeiras','Lisboa','Oeiras','Algés'),
            ('2730-279','Rua dos Engenhos','Lisboa','Oeiras','Barcarena'),
            ('2730-24','Travessa Barreiro','Lisboa','Oeiras','Valejas'),
            ('2790-52','Rua Cravos de Abril','Lisboa','Oeiras','Carnaxide'),
            ('1495-717','Rua Direita do Dafundo','Lisboa','Oeiras','Dafundo'),
            ('2795-83','Rua Doutor Francisco Gentil Martins','Lisboa','Oeiras','Linda a Velha'),
            ('2780-77','Rua Porto Santo','Lisboa','Oeiras','Oeiras'),
            ('2780-322','Avenida Marginal','Lisboa','Oeiras','Oeiras'),
            ('2770-94','Praceta José Epifânio de Abreu','Lisboa','Oeiras','Paço de Arcos'),
            ('2740-78','Rua José Relvas','Lisboa','Oeiras','Leião'),
            ('2740-156','Rua Ribeira','Lisboa','Oeiras','Laje'),
            ('2790-403','Rua Quinta da Telha','Lisboa','Oeiras','Queijas'),
            ('2715-436','Rua do Progresso','Lisboa','Sintra','Camarões'),
            ('2715-351','Largo das Tocas','Lisboa','Sintra','Negrais'),
            ('2605-186','Rua Dom Nuno Álvares Pereira','Lisboa','Sintra','Belas'),
            ('2605-139','Rua da Flor Bela','Lisboa','Sintra','Serra da Silveira'),
            ('2735-429','Rua Camilo Castelo Branco','Lisboa','Sintra','Agualva-Cacém'),
            ('2735-302','Rua Nova do Zambujal','Lisboa','Sintra','Agualva-Cacém'),
            ('2735-188','Rua dos Moleiros','Lisboa','Sintra','Agualva-Cacém'),
            ('2605-772','Rua Frei Gaspar Bernardino','Lisboa','Sintra','Casal de Cambra'),
            ('2705-53','Rua dos Monteiros','Lisboa','Sintra','Almoçageme'),
            ('2705-306','Avenida Eugene Levy','Lisboa','Sintra','Praia das Maçãs'),
            ('2725-689','Urbanização Coopalme','Lisboa','Sintra','Algueirão'),
            ('2725-185','Estrada Nacional 250-1','Lisboa','Sintra','Algueirão'),
            ('2725-278','Travessa de Coudel','Lisboa','Sintra','Mem Martins'),
            ('2725-411','Rua de Pangim','Lisboa','Sintra','Mem Martins'),
            ('2715-53','Rua do Penedo do Lobo','Lisboa','Sintra','Morelena'),
            ('2745-67','Avenida António Ennes','Lisboa','Sintra','Queluz'),
            ('2745-112','Rua de Gago Coutinho e Sacadura Cabral','Lisboa','Sintra','Queluz'),
            ('2745-312','Rua Pedro Nunes','Lisboa','Sintra','Queluz'),
            ('2635-59','Rua do Olival','Lisboa','Sintra','Albarraque'),
            ('2635-620','Avenida de Fitares','Lisboa','Sintra','Rinchoa'),
            ('2635-399','Rua Tristão Vaz Teixeira','Lisboa','Sintra','Rio de Mouro'),
            ('2705-442','Caminho do Areal','Lisboa','Sintra','Assafora'),
            ('2705-582','Caminho da Ribeira da Mata','Lisboa','Sintra','Cortezia'),
            ('2705-730','Largo da Caetana','Lisboa','Sintra','Pobral'),
            ('2710-50','Rua Humberto Delgado','Lisboa','Sintra','Abrunheira'),
            ('2710-247','Avenida 25 de Abril','Lisboa','Sintra','Galamares'),
            ('2710-600','Pátio de Olivença','Lisboa','Sintra','Sintra'),
            ('2710-197','Largo Chão de Meninos','Lisboa','Sintra','Sintra'),
            ('2705-906','Estrada Rio da Mó','Lisboa','Sintra','Terrugem'),
            ('2705-832','Largo da Branca','Lisboa','Sintra','Terrugem'),
            ('2590-74','Casal do Castelo','Lisboa','Sobral de Monte Agraço','Santo Quintino'),
            ('2590-509','Travessa de Nossa Senhora da Luz','Lisboa','Sobral de Monte Agraço','Sobral de Monte Agraço'),
            ('2565-103','Rua Padre José Rodrigues Paula','Lisboa','Torres Vedras','Campelos'),
            ('2565-310','Rua das Florinhas','Lisboa','Torres Vedras','Freiria'),
            ('2565-432','Rua de Nossa Senhora da Assunção','Lisboa','Torres Vedras','Ereira'),
            ('2560-162','Rua Dom Afonso Henriques','Lisboa','Torres Vedras','Ponte do Rol'),
            ('2560-229','Largo de Santo António','Lisboa','Torres Vedras','São Pedro da Cadeira'),
            ('2560-484','Rua Doutor Francisco Sena Esteves','Lisboa','Torres Vedras','Santa Cruz'),
            ('2560-592','Travessa do Cristo','Lisboa','Torres Vedras','Torres Vedras'),
            ('2560-583','Estrada Casal da Torre','Lisboa','Torres Vedras','Torres Vedras'),
            ('2560-237','Travessa da Escolata','Lisboa','Torres Vedras','Torres Vedras'),
            ('2560-367','Travessa do Rosário','Lisboa','Torres Vedras','Torres Vedras'),
            ('2600-418','Rua de Augusto Marcelino Chamusco','Lisboa','Vila Franca de Xira','Alhandra'),
            ('2615-79','Rua Brigadeiro Fernando Alberto de Oliveira','Lisboa','Vila Franca de Xira','Alverca do Ribatejo'),
            ('2615-268','Rua José Viana','Lisboa','Vila Franca de Xira','Alverca do Ribatejo'),
            ('2615-44','Rua Engenheiro Moniz da Maia','Lisboa','Vila Franca de Xira','Alverca do Ribatejo'),
            ('2600-672','Beco Pêro João','Lisboa','Vila Franca de Xira','Castanheira do Ribatejo'),
            ('2625-67','Rua Baptista Pereira','Lisboa','Vila Franca de Xira','Póvoa de Santa Iria'),
            ('2625-87','Rua José Isidro dos Santos','Lisboa','Vila Franca de Xira','Póvoa de Santa Iria'),
            ('2625-572','Avenida Carlos Pinhão','Lisboa','Vila Franca de Xira','Vialonga'),
            ('2625-638','Rua Almada Negreiros','Lisboa','Vila Franca de Xira','Vialonga'),
            ('2600-123','Rua Almirante Cândido dos Reis','Lisboa','Vila Franca de Xira','Vila Franca de Xira'),
            ('2600-775','Rua das Laranjeiras','Lisboa','Vila Franca de Xira','São João dos Montes'),
            ('2650-90','Estrada da Serra da Mira','Lisboa','Amadora','Amadora'),
            ('2650-371','Travessa Augusto Gil','Lisboa','Amadora','Amadora'),
            ('2720-705','Rua Luís Ludovice','Lisboa','Amadora','Amadora'),
            ('2720-138','Avenida dos Cravos Vermelhos','Lisboa','Amadora','Amadora'),
            ('2650-475','Rua do Carrascal','Lisboa','Amadora','Amadora'),
            ('2700-360','Estrada da Falagueira','Lisboa','Amadora','Amadora'),
            ('2650-392','Praceta Amadeu de Sousa Cardoso','Lisboa','Amadora','Amadora'),
            ('2700-590','Praceta Moinho da Boba','Lisboa','Amadora','Amadora'),
            ('2720-458','Praceta do Pombal','Lisboa','Amadora','Amadora'),
            ('1685-520','Rua Engenheiro José Ferreira Roriz','Lisboa','Odivelas','Caneças'),
            ('1685-360','Rua do Aqueduto','Lisboa','Odivelas','Caneças'),
            ('1685-802','Rua General Humberto Delgado','Lisboa','Odivelas','Famões'),
            ('1685-822','Rua Santo Estevão','Lisboa','Odivelas','Famões'),
            ('1685-182','Rua Cidade Peso da Régua','Lisboa','Odivelas','Famões'),
            ('2675-76','Avenida Severiano Pedro Falcão','Lisboa','Odivelas','Odivelas'),
            ('2675-602','Praceta 25 de Agosto','Lisboa','Odivelas','Odivelas'),
            ('2620-502','Rua Pedro Álvares Cabral','Lisboa','Odivelas','Olival Basto'),
            ('1675-29','Rua da Liberdade','Lisboa','Odivelas','Pontinha'),
            ('1675-26','Rua dos Eucaliptos','Lisboa','Odivelas','Pontinha'),
            ('1675-194','Rua Cristóvão da Gama','Lisboa','Odivelas','Pontinha'),
            ('2620-527','Praceta Júlio Peres','Lisboa','Odivelas','Ramada'),
            ('2620-395','Rua Castro da Amoreira','Lisboa','Odivelas','Ramada'),
            ('7370-90','Rua Doutor Carvalho Pereira','Portalegre','Campo Maior','Campo Maior'),
            ('7320-439','Rua da Estrada da Mealhada','Portalegre','Castelo de Vide','Castelo de Vide'),
            ('7430-276','Rua do Picaroto','Portalegre','Crato','Gáfete'),
            ('7350-27','Rua de São Pedro','Portalegre','Elvas','Elvas'),
            ('7350-452','Rua Doutor Manuel Vicente Rosa Marmelo','Portalegre','Elvas','Santa Eulália'),
            ('6040-24','Travessa da Peleteira','Portalegre','Gavião','Belver'),
            ('7330-273','Rua Santo António','Portalegre','Marvão','Santo António das Areias'),
            ('6050-371','Rua Doutor Mário Monteiro','Portalegre','Nisa','Nisa'),
            ('7300-234','Travessa Largo de São Tiago','Portalegre','Portalegre','Portalegre'),
            ('7300-193','Rua Luís Barahona','Portalegre','Portalegre','Portalegre'),
            ('7470-48','Travessa dos Nocturnos','Portalegre','Sousel','Cano'),
            ('4600-41','Quelha das Garridas','Porto','Amarante','Amarante'),
            ('4600-17','Avenida General Silveira','Porto','Amarante','Amarante'),
            ('4605-35','Rua Fontanário do Pinheiro','Porto','Amarante','Vila Meã'),
            ('4600-723','Caminho do Barroco','Porto','Amarante','Salvador do Monte'),
            ('4605-470','Caminho da Portinha','Porto','Amarante','Travanca'),
            ('4600-802','Caminho de Cadafaz','Porto','Amarante','Vila Chã do Marão'),
            ('4600-681','Rua de Troviscais','Porto','Amarante','Lufrei'),
            ('4605-136','Rua Padre António Carvalho','Porto','Amarante','Mancelos'),
            ('4640-141','Rua Engenheiro Adelino Amaro da Costa','Porto','Baião','Baião'),
            ('4640-441','Caminho das Carvalhas','Porto','Baião','Santa Leocádia'),
            ('4640-234','Rua de São João','Porto','Baião','Gestaçô'),
            ('4640-388','Rua do Casal de Queimada','Porto','Baião','Ovil'),
            ('4640-418','Caminho de Jacinto','Porto','Baião','Santa Cruz do Douro'),
            ('4640-479','Caminho dos Plames','Porto','Baião','Santa Marinha do Zêzere'),
            ('4615-307','Travessa de Bouça Chã','Porto','Felgueiras','Borba de Godim'),
            ('4610-195','Rua Leonor Rosa da Silva','Porto','Felgueiras','Felgueiras'),
            ('4610-428','Rua do Pinheiro','Porto','Felgueiras','Lagares'),
            ('4610-547','Calçada de Melo','Porto','Felgueiras','Penacova'),
            ('4650-744','Rua da Seara','Porto','Felgueiras','Varziela'),
            ('4610-567','Rua do Infantário','Porto','Felgueiras','Pinheiro'),
            ('4615-435','Rua de Simães','Porto','Felgueiras','Moure'),
            ('4615-760','Rua Central','Porto','Felgueiras','Vila Verde'),
            ('4650-588','Rua de Lagarto - Espadanal','Porto','Felgueiras','Torrados'),
            ('4435-771','Rua Particular Dom António Castro Meireles','Porto','Gondomar','Baguim do Monte'),
            ('4510-998','Rua Doutor Severiano','Porto','Gondomar','Fânzeres'),
            ('4515-153','Rua das Minas','Porto','Gondomar','Foz Sousa'),
            ('4420-182','Rua de Luanda','Porto','Gondomar','Gondomar'),
            ('4420-6','Rua Engenheiro Adelino Amaro da Costa','Porto','Gondomar','Gondomar'),
            ('4510-105','Rua de Paredes Novas','Porto','Gondomar','Jovim'),
            ('4515-446','Travessa de Cavaleiros','Porto','Gondomar','Medas'),
            ('4515-535','Rua da Mina','Porto','Gondomar','Melres'),
            ('4435-34','Rua Gago Coutinho','Porto','Gondomar','Rio Tinto'),
            ('4435-293','Rua João Casal','Porto','Gondomar','Rio Tinto'),
            ('4510-338','Travessa da Mó','Porto','Gondomar','São Pedro da Cova'),
            ('4420-397','Travessa Camilo Castelo Branco','Porto','Gondomar','Valbom'),
            ('4620-97','Rua de Casais','Porto','Lousada','Casais'),
            ('4620-84','Estrada de Santa Cristina','Porto','Lousada','Nogueira'),
            ('4620-471','Rua da Cruz','Porto','Lousada','Ordem'),
            ('4620-267','Travessa de São Gonçalo','Porto','Lousada','Lustosa'),
            ('4620-624','Travessa de Covas','Porto','Lousada','São Miguel de Lousada'),
            ('4620-926','Travessa Presa da Lameira de Cima','Porto','Lousada','Nevogilde'),
            ('4470-99','Rua Dom Nuno Álvares Pereira','Porto','Maia','Maia'),
            ('4470-78','Rua de Hernâni Pereira Maia','Porto','Maia','Maia'),
            ('4425-206','Rua de Trelaiteiro','Porto','Maia','Maia'),
            ('4425-650','Estrada da Circunvalação','Porto','Maia','Maia'),
            ('4470-842','Rua do Catassol','Porto','Maia','Maia'),
            ('4470-236','Rua das Camélias','Porto','Maia','Maia'),
            ('4425-512','Rua Central de Arcos','Porto','Maia','Maia'),
            ('4475-523','Rua do Canteiro','Porto','Maia','Maia'),
            ('4470-744','Travessa das Bicas','Porto','Maia','Maia'),
            ('4635-133','Travessa do Ladário','Porto','Marco de Canaveses','Constance'),
            ('4630-136','Rua da Ponte','Porto','Marco de Canaveses','Marco de Canaveses'),
            ('4630-78','Rua Urbanização de Vila Verde','Porto','Marco de Canaveses','Marco de Canaveses'),
            ('4625-346','Rua do Emigrante','Porto','Marco de Canaveses','Penha Longa'),
            ('4575-435','Rua do Moirinte','Porto','Marco de Canaveses','Várzea do Douro'),
            ('4625-728','Travessa de Lages','Porto','Marco de Canaveses','Vila Boa do Bispo'),
            ('4575-18','Rua de São Sebastião','Porto','Marco de Canaveses','Alpendorada e Matos'),
            ('4635-716','Travessa de Marecos','Porto','Marco de Canaveses','Vila Boa de Quires'),
            ('4635-638','Travessa de Revinhas','Porto','Marco de Canaveses','Várzea da Ovelha E Aliviada'),
            ('4630-687','Rua do Juncal','Porto','Marco de Canaveses','Soalhães'),
            ('4630-537','Avenida Avelino Ferreira Torres','Porto','Marco de Canaveses','Paredes de Viadores'),
            ('4460-833','Rua Teixeira Lopes','Porto','Matosinhos','Custóias'),
            ('4460-98','Rua do Regadio','Porto','Matosinhos','Guifões'),
            ('4455-164','Rua Maria do Carmo Freire','Porto','Matosinhos','Lavra'),
            ('4465-680','Rua Dom Frei Almeida Vasconcelos','Porto','Matosinhos','Leça do Balio'),
            ('4450-644','Rua do Corpo Santo','Porto','Matosinhos','Matosinhos'),
            ('4450-38','Rua Álvaro Castelões','Porto','Matosinhos','Matosinhos'),
            ('4450-390','Bairro Benjamim Grandeiro','Porto','Matosinhos','Matosinhos'),
            ('4455-266','Itinerário Complementar 1','Porto','Matosinhos','Perafita'),
            ('4455-792','Travessa de Aguiar','Porto','Matosinhos','Santa Cruz do Bispo'),
            ('4465-170','Rua Honório de Lima','Porto','Matosinhos','São Mamede de Infesta'),
            ('4460-334','Rua de João Mendonça','Porto','Matosinhos','Senhora da Hora'),
            ('4460-366','Travessa Nova do Seixo','Porto','Matosinhos','Senhora da Hora'),
            ('4595-327','Via Panorâmica','Porto','Paços de Ferreira','Eiriz'),
            ('4595-121','Travessa da Devesa','Porto','Paços de Ferreira','Frazão'),
            ('4590-373','Rua Alto da Paixão','Porto','Paços de Ferreira','Freamunde'),
            ('4590-489','Travessa do Paião','Porto','Paços de Ferreira','Modelos'),
            ('4590-684','Rua das Bicas','Porto','Paços de Ferreira','Raimonda'),
            ('4590-829','Rua do Centro Paroquial','Porto','Paços de Ferreira','Ferreira'),
            ('4590-882','Rua da Fonte de Salgueirais','Porto','Paços de Ferreira','Lamoso'),
            ('4595-302','Calçada de Escariz','Porto','Paços de Ferreira','Penamaior'),
            ('4580-177','Rua Nova Torre da Madureira','Porto','Paredes','Beire'),
            ('4580-329','Rua das Cavadas','Porto','Paredes','Cete'),
            ('4585-71','Rua dos Carteiros','Porto','Paredes','Gandra'),
            ('4585-355','Rua Particular','Porto','Paredes','Gandra'),
            ('4580-487','Rua Padre Floriano','Porto','Paredes','Lordelo'),
            ('4585-883','Rua Alto do Carvalhinho','Porto','Paredes','Parada de Todeia'),
            ('4585-850','Rotunda da Cadeireira','Porto','Paredes','Rebordosa'),
            ('4585-876','Rua Enfermeira Dona Teresinha Leal','Porto','Paredes','Rebordosa'),
            ('4585-632','Rua Estreita','Porto','Paredes','Recarei'),
            ('4580-747','Rua da Almuinha','Porto','Paredes','Sobrosa'),
            ('4585-735','Rua do Bacelo','Porto','Paredes','Vandoma'),
            ('4580-657','Travessinha da Estrada','Porto','Paredes','Vilela'),
            ('4575-97','Rua do Outeiro','Porto','Penafiel','Boelhe'),
            ('4575-218','Avenida Doutor Carvalho Mendes','Porto','Penafiel','Eja'),
            ('4560-233','Rua Aldeia de Cima','Porto','Penafiel','Milhundos'),
            ('4560-358','Rua das Mimosas','Porto','Penafiel','Paço de Sousa'),
            ('4560-531','Rua da Saudade','Porto','Penafiel','Penafiel'),
            ('4575-543','Travessa de Valmourisco','Porto','Penafiel','Sebolido'),
            ('4560-871','Caminho de Ranhoses','Porto','Penafiel','Vila Cova'),
            ('4575-194','Rua das Casas da Serra','Porto','Penafiel','Canelas'),
            ('4560-195','Rua de Arques','Porto','Penafiel','Lagares'),
            ('4560-815','Rua do Enxidro','Porto','Penafiel','São Martinho de Recezinhos'),
            ('4575-279','Rua do Alambique','Porto','Penafiel','Oldrões'),
            ('4575-127','Rua de Casal','Porto','Penafiel','Cabeça Santa'),
            ('4560-112','Rua de Campo Grande','Porto','Penafiel','Fonte Arcada'),
            ('4049-56','Rua Joaquim António de Aguiar','Porto','Porto','Porto'),
            ('4150-358','Avenida Marechal Gomes da Costa','Porto','Porto','Porto'),
            ('4300-342','Rua Monte da Estação','Porto','Porto','Porto'),
            ('4050-447','Rua Oliveira Monteiro','Porto','Porto','Porto'),
            ('4000-382','Rua de Passos Manuel','Porto','Porto','Porto'),
            ('4000-0','Largo 1º de Dezembro','Porto','Porto','Porto'),
            ('4050-527','Rua Sá Noronha','Porto','Porto','Porto'),
            ('4200-484','Rua São Jorge','Porto','Porto','Porto'),
            ('4250-481','Rua de Sousa Pinto','Porto','Porto','Porto'),
            ('4300-10','Rotunda do Freixo','Porto','Porto','Porto'),
            ('4250-181','Rua Doutor Cruz Malpique','Porto','Porto','Porto'),
            ('4250-76','Rua Escultor Barata Feyo','Porto','Porto','Porto'),
            ('4250-81','Rua Bordeaux','Porto','Porto','Porto'),
            ('4050-20','Rua das Águas Férreas','Porto','Porto','Porto'),
            ('4050-197','Escadas Cidral de Cima','Porto','Porto','Porto'),
            ('4200-206','Travessa Cortes','Porto','Porto','Porto'),
            ('4200-257','Rua Desertas','Porto','Porto','Porto'),
            ('4000-33','Rua da Alegria','Porto','Porto','Porto'),
            ('4300-169','Rua Escolas','Porto','Porto','Porto'),
            ('4350-413','Alameda das Antas','Porto','Porto','Porto'),
            ('4169-1','Rua Gonçalo Sampaio','Porto','Porto','Porto'),
            ('4570-48','Beco de Guardinhos','Porto','Póvoa de Varzim','Balazar'),
            ('4570-336','Rua dos Mirandas','Porto','Póvoa de Varzim','Laundos'),
            ('4490-641','Rua Gomes de Amorim','Porto','Póvoa de Varzim','Póvoa de Varzim'),
            ('4490-512','Rua da Galé','Porto','Póvoa de Varzim','Póvoa de Varzim'),
            ('4490-500','Rua da Caverneira','Porto','Póvoa de Varzim','Póvoa de Varzim'),
            ('4570-431','Rua da Fonte da Granja','Porto','Póvoa de Varzim','Rates'),
            ('4825-39','Rua Poço da Moira','Porto','Santo Tirso','Agrela'),
            ('4795-143','Travessa dos Moínhos do Ave','Porto','Santo Tirso','Vila das Aves'),
            ('4780-782','Largo do Bacelo','Porto','Santo Tirso','Burgães'),
            ('4795-225','Rua da Quintinha','Porto','Santo Tirso','Rebordões'),
            ('4795-363','Travessa do Mirante','Porto','Santo Tirso','Roriz'),
            ('4780-575','Travessa dos Mulatinhos','Porto','Santo Tirso','Santo Tirso'),
            ('4795-429','Travessa 2 da Rua de Santo Isidro','Porto','Santo Tirso','São Mamede de Negrelos'),
            ('4795-733','Travessa Lameiro das Rolas','Porto','Santo Tirso','São Tomé'),
            ('4795-831','Rua Parque Chefe Armindo','Porto','Santo Tirso','Vilarinho'),
            ('4825-285','Rua de Real','Porto','Santo Tirso','Monte Córdova'),
            ('4445-83','Rua das Cruzes','Porto','Valongo','Alfena'),
            ('4440-196','Travessa do Borbulhão','Porto','Valongo','Campo'),
            ('4445-364','Rua Camilo Castelo Branco','Porto','Valongo','Ermesinde'),
            ('4445-555','Rua do Passal','Porto','Valongo','Ermesinde'),
            ('4440-366','Rua Dom João de Castro','Porto','Valongo','Sobrado'),
            ('4440-627','Rua do Terreiro','Porto','Valongo','Valongo'),
            ('4480-40','Rua Dona Maria Alice dos Reis Ferreira','Porto','Vila do Conde','Arcos'),
            ('4480-177','Travessa Casa da Praça','Porto','Vila do Conde','Azurara'),
            ('4485-159','Travessa do Ergal','Porto','Vila do Conde','Fornelo'),
            ('4480-316','Travessa do Monte','Porto','Vila do Conde','Junqueira'),
            ('4485-627','Rua Saúl Dias','Porto','Vila do Conde','Mindelo'),
            ('4480-382','Travessa Nº 1 do Outeiro','Porto','Vila do Conde','Retorta'),
            ('4480-590','Rua de Nossa Senhora do Resgate','Porto','Vila do Conde','Touguinhó'),
            ('4480-740','Rua Comendador António Fernandes da Costa','Porto','Vila do Conde','Vila do Conde'),
            ('4480-794','Rotunda do Professor','Porto','Vila do Conde','Vila do Conde'),
            ('4410-456','Travessa de Arco','Porto','Vila Nova de Gaia','Arcozelo'),
            ('4410-328','Beco do Redondelo','Porto','Vila Nova de Gaia','Arcozelo'),
            ('4430-799','Rua 5 de Outubro','Porto','Vila Nova de Gaia','Avintes'),
            ('4410-229','Rua Delfim Lima','Porto','Vila Nova de Gaia','Canelas'),
            ('4415-480','Rua da Lage','Porto','Vila Nova de Gaia','Grijó'),
            ('4415-661','Rua da Agra','Porto','Vila Nova de Gaia','Lever'),
            ('4415-175','Rua do Bom Samaritano','Porto','Vila Nova de Gaia','Pedroso'),
            ('4415-215','Rua dos Virtudes','Porto','Vila Nova de Gaia','Pedroso'),
            ('4415-406','Avenida Jaime Isidoro','Porto','Vila Nova de Gaia','Perosinho'),
            ('4410-211','Avenida dos Árvores','Porto','Vila Nova de Gaia','São Félix da Marinha'),
            ('4415-944','Rua Além Rio','Porto','Vila Nova de Gaia','Seixezelo'),
            ('4405-727','Beco do Rego da Água','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4430-390','Praceta de Escola','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4430-554','Travessa Tapada','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4405-694','Rua da Presa','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4405-541','Travessa da Carreira Funda','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4405-891','Travessa de Painçal','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4430-42','Rua Manuel Cardoso Martins','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4434-501','Avenida da República','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4430-0','Rua 20 de Junho','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4400-55','Rua de Bélgica','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4400-552','Rua de Pinheiral','Porto','Vila Nova de Gaia','Vila Nova de Gaia'),
            ('4745-499','Rua de São Roque','Porto','Trofa','São Mamede Coronado'),
            ('4785-308','Rua Dom Pedro V','Porto','Trofa','São Martinho Bougado'),
            ('4745-74','Travessa São João','Porto','Trofa','Alvarelhos'),
            ('4745-355','Rua Alto Vilares','Porto','Trofa','Muro'),
            ('4785-706','Rua Comércio','Porto','Trofa','Santiago do Bougado'),
            ('2205-60','Travessa do Ringue','Santarém','Abrantes','Abrantes'),
            ('2200-428','Rua Monteiro Lima','Santarém','Abrantes','Abrantes'),
            ('2205-501','Rua do Cabeço','Santarém','Abrantes','Bicas'),
            ('2380-0','Rua 25 de Abril','Santarém','Alcanena','Alcanena'),
            ('2380-528','Rua de São Vicente','Santarém','Alcanena','Malhou'),
            ('2380-647','Rua das Irmãs Paulas','Santarém','Alcanena','Vila Moreira'),
            ('2080-162','Rua Padre António Vieira','Santarém','Almeirim','Almeirim'),
            ('2130-361','Rua de Nossa Senhora do Castelo','Santarém','Benavente','Benavente'),
            ('2135-150','Rua Francisco Maria Gomes','Santarém','Benavente','Porto Alto'),
            ('2135-302','Rua Aristides de Sousa Mendes','Santarém','Benavente','Samora Correia'),
            ('2070-134','Travessa do Comendador','Santarém','Cartaxo','Cartaxo'),
            ('2070-398','Praça Serpa Pinto','Santarém','Cartaxo','Pontével'),
            ('2140-609','Rua 25 de Abril','Santarém','Chamusca','Arrepiado'),
            ('2250-366','Rua dos Combatentes','Santarém','Constância','Aldeia de Santa Margarida'),
            ('2100-515','Rua do Monte','Santarém','Coruche','Fajarda'),
            ('2330-79','Praça da República','Santarém','Entroncamento','Entroncamento'),
            ('2150-168','Rua Dom Afonso Henriques','Santarém','Golegã','Golegã'),
            ('6120-538','Rua da Lomba','Santarém','Mação','Ortiga'),
            ('2040-238','Rua da Cidade de Santarém','Santarém','Rio Maior','Rio Maior'),
            ('2120-187','Rua dos Foros Novos','Santarém','Salvaterra de Magos','Foros de Salvaterra'),
            ('2125-184','Rua José Norte','Santarém','Salvaterra de Magos','Marinhais'),
            ('2120-66','Estrada dos Ramalhais','Santarém','Salvaterra de Magos','Salvaterra de Magos'),
            ('2025-310','Rua António Neves','Santarém','Santarém','Amiais de Baixo'),
            ('2000-494','Travessa de Santana','Santarém','Santarém','Pernes'),
            ('2000-179','Avenida Dom Afonso Henriques','Santarém','Santarém','Santarém'),
            ('2005-361','Avenida dos Combatentes','Santarém','Santarém','Santarém'),
            ('2005-418','Rua da Escola Nova','Santarém','Santarém','Vale de Santarém'),
            ('2230-223','Rua do Outeiro da Velha','Santarém','Sardoal','Sardoal'),
            ('2300-482','Rua Diogo de Arruda','Santarém','Tomar','Tomar'),
            ('2350-250','Rua Ana da Tecedeira','Santarém','Torres Novas','Pedrógão'),
            ('2350-450','Rua Padre Júlio Duque','Santarém','Torres Novas','Torres Novas'),
            ('2350-868','Estrada Nacional 3','Santarém','Torres Novas','Botequim'),
            ('2260-600','Rua Dom Afonso Henriques','Santarém','Vila Nova da Barquinha','Moita do Norte'),
            ('2490-62','Rua Padre Moreira','Santarém','Ourém','Atouguia'),
            ('2495-302','Rua do Casal Grande','Santarém','Ourém','Alveijar'),
            ('2490-246','Rua dos Algares','Santarém','Ourém','Ourém'),
            ('2490-423','Rua do Pomarinho','Santarém','Ourém','Ourém'),
            ('2490-565','Rua Tenente Coronel Moreira Lopes','Santarém','Ourém','Ourém'),
            ('2435-599','Rua Luís de Camões','Santarém','Ourém','Peras Ruivas'),
            ('2435-34','Rua da Eira Velha','Santarém','Ourém','Casal dos Bernardos'),
            ('7595-102','Largo de São Francisco','Setúbal','Alcácer do Sal','Torrão'),
            ('7580-199','Bairro do Bailador','Setúbal','Alcácer do Sal','Alcácer do Sal'),
            ('2890-236','Rua do Poder Local','Setúbal','Alcochete','Samouco'),
            ('2800-676','Rua Carvalho Freirinha','Setúbal','Almada','Almada'),
            ('2800-118','Rua Dom José de Mascarenhas','Setúbal','Almada','Almada'),
            ('2805-142','Rua Francisco Ferrer','Setúbal','Almada','Almada'),
            ('2800-697','Rua Luís de Queiroz','Setúbal','Almada','Almada'),
            ('2805-236','Largo da Romeira','Setúbal','Almada','Almada'),
            ('2825-66','Rua do Chafariz Público','Setúbal','Almada','Monte de Caparica'),
            ('2825-48','Rua do Funchalinho','Setúbal','Almada','Vila Nova de Caparica'),
            ('2820-46','Rua Avelino Cunhal','Setúbal','Almada','Aroeira'),
            ('2825-343','Rua Joaquim da Matosa','Setúbal','Almada','Costa de Caparica'),
            ('2815-757','Rua Professor Egas Moniz','Setúbal','Almada','Sobreda'),
            ('2815-620','Rua Quinta do Secretário','Setúbal','Almada','Sobreda'),
            ('2825-894','Avenida 25 de Abril','Setúbal','Almada','Trafaria'),
            ('2820-416','Rua José Dias Coelho','Setúbal','Almada','Charneca de Caparica'),
            ('2820-187','Rua Pedro Costa','Setúbal','Almada','Charneca de Caparica'),
            ('2820-7','Rua dos Zimbros','Setúbal','Almada','Charneca de Caparica'),
            ('2820-2','Rua Afonso Lopes Vieira','Setúbal','Almada','Charneca de Caparica'),
            ('2830-345','Rua General Norton de Matos','Setúbal','Barreiro','Barreiro'),
            ('2830-280','Rua Dom Nuno Álvares Pereira','Setúbal','Barreiro','Barreiro'),
            ('2830-446','Rua 20 de Abril','Setúbal','Barreiro','Palhais'),
            ('2835-469','Rua das Giestas','Setúbal','Barreiro','Vila Chã'),
            ('7570-129','Jardim Doutor Jacinto Nunes','Setúbal','Grândola','Grândola'),
            ('2860-28','Largo do Descarregador','Setúbal','Moita','Alhos Vedros'),
            ('2860-213','Estrada do Pinhal do Quadrado','Setúbal','Moita','Barra Cheia'),
            ('2860-636','Rua da Liberdade','Setúbal','Moita','Rosário'),
            ('2864-7','Praça da República','Setúbal','Moita','Moita'),
            ('2835-217','Praceta João de Santarém','Setúbal','Moita','Vale da Amoreira'),
            ('2870-706','Largo da Feira','Setúbal','Montijo','Atalaia'),
            ('2870-36','Rua Palmira Bastos','Setúbal','Montijo','Montijo'),
            ('2870-13','Rua Paiva Couceiro','Setúbal','Montijo','Montijo'),
            ('2965-213','Estrada Nacional 5','Setúbal','Palmela','Agualva de Cima'),
            ('2950-135','Rua Joaquim Maria Afonso','Setúbal','Palmela','Lau'),
            ('2955-205','Rua Luís de Camões','Setúbal','Palmela','Pinhal Novo'),
            ('2965-211','Rua João Isidro Dias','Setúbal','Palmela','Asseiceira'),
            ('2950-535','Praceta Tristão Vaz Teixeira','Setúbal','Palmela','Quinta do Anjo'),
            ('2950-595','Rua Norton de Matos','Setúbal','Palmela','Quinta do Anjo'),
            ('7565-48','Rua da Figueira','Setúbal','Santiago do Cacém','Alvalade'),
            ('7565-214','Rua 33','Setúbal','Santiago do Cacém','Ermidas do Sado'),
            ('7540-107','Rua do Rio da Velha','Setúbal','Santiago do Cacém','Santiago do Cacém'),
            ('7500-190','Largo do Pinhal da Zorra','Setúbal','Santiago do Cacém','Vila Nova de Santo André'),
            ('2840-58','Avenida Vasco da Gama','Setúbal','Seixal','Foros da Catrapona'),
            ('2845-431','Praceta Joaquim Batista Pereira','Setúbal','Seixal','Amora'),
            ('2845-123','Rua Pedro Julião','Setúbal','Seixal','Cruz de Pau'),
            ('2845-298','Rua Lindley Cintra','Setúbal','Seixal','Foros de Amora'),
            ('2855-17','Rua Bocage','Setúbal','Seixal','Corroios'),
            ('2855-248','Rua Soeiro Pereira Gomes','Setúbal','Seixal','Miratejo'),
            ('2855-730','Rua Manuela Margarido','Setúbal','Seixal','Vale de Milhaços'),
            ('2865-768','Parque do Rego Travesso','Setúbal','Seixal','Fernão Ferro'),
            ('2865-409','Rua Almada Negreiros','Setúbal','Seixal','Fernão Ferro'),
            ('2865-609','Rua António Aleixo','Setúbal','Seixal','Fernão Ferro'),
            ('2865-655','Rua Florbela Espanca','Setúbal','Seixal','Fernão Ferro'),
            ('2865-670','Rua João Villaret','Setúbal','Seixal','Fernão Ferro'),
            ('2865-632','Rua da República','Setúbal','Seixal','Fernão Ferro'),
            ('2865-642','Rua Dom João I','Setúbal','Seixal','Fernão Ferro'),
            ('2865-39','Rua 25 de Abril','Setúbal','Seixal','Fernão Ferro'),
            ('2865-636','Rua Dom Dinis','Setúbal','Seixal','Fernão Ferro'),
            ('2865-327','Rua Raquel Bastos','Setúbal','Seixal','Pinhal General'),
            ('2865-644','Rua Fernando Pessoa','Setúbal','Seixal','Quinta das Laranjeiras'),
            ('2865-460','Rua dos Loureiros','Setúbal','Seixal','Quinta das Laranjeiras'),
            ('2840-506','Rua António Pedro','Setúbal','Seixal','Arrentela'),
            ('2840-735','Avenida José Afonso','Setúbal','Seixal','Cavaquinhas'),
            ('2840-721','Avenida 25 de Abril','Setúbal','Seixal','Torre da Marinha'),
            ('2975-314','Rua Afonso Costa','Setúbal','Sesimbra','Quinta do Conde'),
            ('2975-185','Rua do Girassol','Setúbal','Sesimbra','Quinta do Conde'),
            ('2975-147','Rua Rio Mondego','Setúbal','Sesimbra','Quinta do Conde'),
            ('2975-301','Rua Sousa Martins','Setúbal','Sesimbra','Quinta do Conde'),
            ('2970-218','Rua Pinhal de Cima','Setúbal','Sesimbra','Pinhal do Cabedal'),
            ('2970-292','Avenida Luís Vaz de Camões','Setúbal','Sesimbra','Cotovia'),
            ('2970-395','Travessa do Castelinho','Setúbal','Sesimbra','Lagoa de Albufeira'),
            ('2970-93','Rua Branca de Gonta Colaço','Setúbal','Sesimbra','Santana'),
            ('2970-530','Rua das Barcas','Setúbal','Sesimbra','Sesimbra'),
            ('2900-244','Rua Ariovisto José Valério','Setúbal','Setúbal','Setúbal'),
            ('2900-714','Rua Mário Caes Esteves','Setúbal','Setúbal','Setúbal'),
            ('2910-734','Praceta Miguel Torga','Setúbal','Setúbal','Setúbal'),
            ('2910-220','Rua dos Cravos','Setúbal','Setúbal','Setúbal'),
            ('2910-279','Estrada de Algeruz','Setúbal','Setúbal','Setúbal'),
            ('2904-530','Rua Álvaro Castelões','Setúbal','Setúbal','Setúbal'),
            ('2910-644','Rua dos 4 Caminhos','Setúbal','Setúbal','Setúbal'),
            ('2914-515','Rua do Alto da Guerra','Setúbal','Setúbal','Setúbal'),
            ('2925-327','Rua Filipa de Lencastre','Setúbal','Setúbal','Azeitão'),
            ('2925-301','Travessa do Vale da Roupa','Setúbal','Setúbal','Azeitão'),
            ('2925-6','Rua Padre Vicente de Campos','Setúbal','Setúbal','Oleiros'),
            ('7520-415','Rua Joaquim Augusto','Setúbal','Sines','Porto Covo'),
            ('7520-104','Avenida General Humberto Delgado','Setúbal','Sines','Sines'),
            ('4910-106','Avenida Padre Pinheiro','Viana do Castelo','Caminha','Caminha'),
            ('4910-277','Urbanização da Fontela','Viana do Castelo','Caminha','Moledo'),
            ('4910-609','Rua do Castelo da Pena','Viana do Castelo','Caminha','Vilarelho'),
            ('4910-339','Travessa Mário \' Carriço \' Azevedo','Viana do Castelo','Caminha','Seixas'),
            ('4910-303','Beco das Dias','Viana do Castelo','Caminha','Orbacém'),
            ('4950-616','Caminho de Santa Lúzia','Viana do Castelo','Monção','Moreira'),
            ('4940-533','Rua Doutor Aquilino Ribeiro','Viana do Castelo','Paredes de Coura','Paredes de Coura'),
            ('4990-683','Rua da Covinha','Viana do Castelo','Ponte de Lima','Poiares'),
            ('4990-158','Quelha da Vila Velha','Viana do Castelo','Ponte de Lima','Ponte de Lima'),
            ('4990-500','Rua da Igreja','Viana do Castelo','Ponte de Lima','Anais'),
            ('4930-96','Rua da Atalaia','Viana do Castelo','Valença','Cerdal'),
            ('4930-556','Caminho das Arregadas','Viana do Castelo','Valença','Taião'),
            ('4930-411','Carreiro da Ponte','Viana do Castelo','Valença','Gondomil'),
            ('4900-12','Caminho do Sanguinhal','Viana do Castelo','Viana do Castelo','Afife'),
            ('4905-513','Rua Cancela da Serra','Viana do Castelo','Viana do Castelo','Mujães'),
            ('4925-581','Bairro do Moinho Novo','Viana do Castelo','Viana do Castelo','Perre'),
            ('4900-6','Rua Maria Manuela Couto Viana','Viana do Castelo','Viana do Castelo','Viana do Castelo'),
            ('4935-67','Rua Doutor Carteado Monteiro','Viana do Castelo','Viana do Castelo','Viana do Castelo'),
            ('4900-788','Rua de Portuzelo','Viana do Castelo','Viana do Castelo','Viana do Castelo'),
            ('4900-491','Largo Trindade Coelho','Viana do Castelo','Viana do Castelo','Viana do Castelo'),
            ('4925-148','Travessa da Chão','Viana do Castelo','Viana do Castelo','Viana do Castelo'),
            ('4925-657','Largo Senhora da Encarnação','Viana do Castelo','Viana do Castelo','Vila Mou'),
            ('4905-651','Rua Matias dos Santos','Viana do Castelo','Viana do Castelo','Vila de Punhe'),
            ('4905-554','Travessa das Urzes','Viana do Castelo','Viana do Castelo','Santa Leocádia de Geraz do Lima'),
            ('4925-415','Estrada da Granja','Viana do Castelo','Viana do Castelo','Lanheses'),
            ('4905-344','Rua Agra da Várzea','Viana do Castelo','Viana do Castelo','Barroselas'),
            ('4900-281','Rua da Caneja','Viana do Castelo','Viana do Castelo','Carreço'),
            ('4925-503','Rua do Moínho da Mata','Viana do Castelo','Viana do Castelo','Nogueira'),
            ('4925-456','Escadinhas da Igreja','Viana do Castelo','Viana do Castelo','Meixedo'),
            ('4925-553','Beco do Resineiro','Viana do Castelo','Viana do Castelo','Outeiro'),
            ('4925-362','Rua da Castanheira','Viana do Castelo','Viana do Castelo','Freixieiro de Soutelo'),
            ('4905-253','Caminho de Casais','Viana do Castelo','Viana do Castelo','Deão'),
            ('4925-473','Estrada da Senhora do Minho','Viana do Castelo','Viana do Castelo','Montaria'),
            ('4920-78','Travessa dos Pardinheiros','Viana do Castelo','Vila Nova de Cerveira','Lovelhe'),
            ('4920-65','Rua do Cruzeiro','Viana do Castelo','Vila Nova de Cerveira','Gondarém'),
            ('5070-225','Largo Capitão Lopes Praça','Vila Real','Alijó','Castedo'),
            ('5400-86','Avenida Padre António Vieira','Vila Real','Chaves','Chaves'),
            ('5400-304','Ilha Cavaleiro','Vila Real','Chaves','Chaves'),
            ('5400-520','Rua Capitão Sousa Dias','Vila Real','Chaves','Chaves'),
            ('5400-624','Beco da Ribeira de São Paio','Vila Real','Chaves','São Lourenço'),
            ('5400-750','Rua São Mateus','Vila Real','Chaves','Santo Estevão'),
            ('5400-673','Rua Central','Vila Real','Chaves','Outeiro Seco'),
            ('5470-41','Travessa da Fecha','Vila Real','Montalegre','Cambeses do Rio'),
            ('5050-272','Rua dos Camilos','Vila Real','Peso da Régua','Peso da Régua'),
            ('5030-132','Rua de Soutelo','Vila Real','Santa Marta de Penaguião','Fontes'),
            ('5030-452','Caminho do Navalho','Vila Real','Santa Marta de Penaguião','Santa Marta de Penaguião'),
            ('5430-464','Rua do Pombal','Vila Real','Valpaços','Valpaços'),
            ('5450-18','Rua Dom Afonso II','Vila Real','Vila Pouca de Aguiar','Vila Pouca de Aguiar'),
            ('5000-81','Rua São Frutuoso','Vila Real','Vila Real','Constantim'),
            ('5000-0','Rua Dom António Valente da Fonseca','Vila Real','Vila Real','Vila Real'),
            ('5000-646','Largo dos Moinhos','Vila Real','Vila Real','Vila Real'),
            ('5110-673','Rua Remígio','Viseu','Armamar','Vila Seca'),
            ('3430-59','Rua Lages','Viseu','Carregal do Sal','Carregal do Sal'),
            ('3430-749','Rua Nossa Senhora Ribeira','Viseu','Carregal do Sal','Parada'),
            ('3600-403','Rua Padre Adelino Duarte Ribeiro','Viseu','Castro Daire','Mézio'),
            ('5100-114','Rua Arribada','Viseu','Lamego','Lamego'),
            ('3530-61','Rua do Adro','Viseu','Mangualde','Espinho'),
            ('3530-92','Rua Santa Catarina','Viseu','Mangualde','Mangualde'),
            ('3525-507','Beco Sacadura Botte','Viseu','Nelas','Aguieira'),
            ('3525-637','Rua dos Emigrantes','Viseu','Nelas','Lapa do Lobo'),
            ('3630-295','Rua do Casal','Viseu','Penedono','Penela da Beira'),
            ('3440-378','Rua Gago Coutinho','Viseu','Santa Comba Dão','Santa Comba Dão'),
            ('5130-54','Rua da Romanzeira','Viseu','São João da Pesqueira','Casais do Douro'),
            ('3660-463','Rua da Amizade','Viseu','São Pedro do Sul','São Pedro do Sul'),
            ('3640-89','Rua do Centro Social','Viseu','Sernancelhe','Ferreirim'),
            ('5120-181','Terreiro do Visconde','Viseu','Tabuaço','Granja do Tedo'),
            ('3610-33','Rua da Ribeiro','Viseu','Tarouca','Gouviães'),
            ('3460-586','Rua C','Viseu','Tondela','Tondela'),
            ('3650-214','Rua Doutor Vasco dos Santos Teles','Viseu','Vila Nova de Paiva','Vila Nova de Paiva'),
            ('3515-650','Largo do Ferreiro','Viseu','Viseu','Travanca da Bodiosa'),
            ('3505-236','Largo 25 de Abril','Viseu','Viseu','Sanguinhedo'),
            ('3505-265','Bairro Familiar','Viseu','Viseu','Carragoso'),
            ('3510-884','Avenida da Via Rápida','Viseu','Viseu','Vila Chã do Monte'),
            ('3515-374','Estrada de São Gens','Viseu','Viseu','Viseu'),
            ('3510-8','Rua Nova da Balsa','Viseu','Viseu','Viseu'),
            ('3510-927','Rua dos Cruzeiros','Viseu','Viseu','Viseu'),
            ('3505-504','Quinta Alto dos Lagares','Viseu','Viseu','Viseu'),
            ('3510-13','Rua do Coração de Jesus','Viseu','Viseu','Viseu'),
            ('3505-545','Estrada da Ramalhosa','Viseu','Viseu','Viseu'),
            ('3510-40','Travessa Alexandre Herculano','Viseu','Viseu','Viseu'),
            ('3505-490','Largo São Frutuoso','Viseu','Viseu','Viseu'),
            ('3505-563','Rua da Lapa','Viseu','Viseu','Viseu'),
            ('9370-814','Caminho do Lombo Saro','Ilha da Madeira','Calheta (Madeira)','Fajã da Ovelha'),
            ('9370-726','Vereda Morno','Ilha da Madeira','Calheta (Madeira)','Arco da Calheta'),
            ('9370-768','Vereda São João','Ilha da Madeira','Calheta (Madeira)','Calheta'),
            ('9385-263','Impasse Mourro Trigo','Ilha da Madeira','Calheta (Madeira)','Ponta do Pargo'),
            ('9300-345','Vereda Lombo do Pedregal','Ilha da Madeira','Câmara de Lobos','Câmara de Lobos'),
            ('9030-332','Vereda da Fajã Capitão','Ilha da Madeira','Câmara de Lobos','Curral das Freiras'),
            ('9325-371','Estrada Nova do Pedregal','Ilha da Madeira','Câmara de Lobos','Estreito Câmara de Lobos'),
            ('9325-132','Largo Chote','Ilha da Madeira','Câmara de Lobos','Jardim da Serra'),
            ('9004-542','Avenida Infante','Ilha da Madeira','Funchal','Funchal'),
            ('9000-136','Caminho Pilar','Ilha da Madeira','Funchal','Funchal'),
            ('9020-189','Vereda do Corgo','Ilha da Madeira','Funchal','Funchal'),
            ('9060-25','Caminho Palheiro','Ilha da Madeira','Funchal','Funchal'),
            ('9020-272','Vereda Capitoa','Ilha da Madeira','Funchal','Funchal'),
            ('9050-209','Estrada dos Marmeleiros','Ilha da Madeira','Funchal','Funchal'),
            ('9060-67','Rua Cidade Maui','Ilha da Madeira','Funchal','Funchal'),
            ('9060-156','Rua Padre Laurindo','Ilha da Madeira','Funchal','Funchal'),
            ('9050-516','Vereda do Miradouro','Ilha da Madeira','Funchal','Funchal'),
            ('9200-149','Caminho do Moledo','Ilha da Madeira','Machico','Machico'),
            ('9360-361','Estrada Engenheiro Teixeira de Sousa','Ilha da Madeira','Ponta do Sol','Canhas'),
            ('9360-413','Vereda do Bacelo','Ilha da Madeira','Ponta do Sol','Madalena do Mar'),
            ('9350-323','Caminho da Pereira','Ilha da Madeira','Ribeira Brava','Serra de Água'),
            ('9125-35','Impasse Vinha Velha','Ilha da Madeira','Santa Cruz','Caniço'),
            ('9125-212','Impasse Urbanização Ferreira','Ilha da Madeira','Santa Cruz','Caniço'),
            ('9100-190','Caminho dos Ligeiros','Ilha da Madeira','Santa Cruz','Santa Cruz'),
            ('9400-10','Estrada Velha da Camacha','Ilha de Porto Santo','Porto Santo','Porto Santo'),
            ('9400-202','Rua da Circunscrição','Ilha de Porto Santo','Porto Santo','Porto Santo'),
            ('9560-222','Rua Caminho do Mato ao Jardim','Ilha de São Miguel','Lagoa (São Miguel)','Água de Pau'),
            ('9560-125','Travessa da Relvinha','Ilha de São Miguel','Lagoa (São Miguel)','Lagoa'),
            ('9545-18','Canada do Medeiroa de Baixo','Ilha de São Miguel','Ponta Delgada','Ajuda'),
            ('9555-143','Rua da Esquina','Ilha de São Miguel','Ponta Delgada','Mosteiros'),
            ('9500-557','Rua do Pico','Ilha de São Miguel','Ponta Delgada','Feteiras'),
            ('9504-520','Largo Mártires da Pátria','Ilha de São Miguel','Ponta Delgada','Ponta Delgada'),
            ('9500-105','Rua Doutor Carlos Machado','Ilha de São Miguel','Ponta Delgada','Ponta Delgada'),
            ('9545-418','Rua Cónego Arruda','Ilha de São Miguel','Ponta Delgada','Santo António'),
            ('9625-410','Canada das Gentes','Ilha de São Miguel','Ribeira Grande','Porto Formoso'),
            ('9600-554','Rua Eduino Rocha','Ilha de São Miguel','Ribeira Grande','Ribeira Grande'),
            ('9680-509','Canada Mestre Agostinho','Ilha de São Miguel','Vila Franca do Campo','Ribeira das Taínhas'),
            ('9700-114','Rua da Malagueta','Ilha Terceira','Angra do Heroísmo','Angra do Heroísmo'),
            ('9760-287','Rua Nova','Ilha Terceira','Praia da Vitória','Lajes'),
            ('9880-350','Travessa da Guia','Ilha da Graciosa','Santa Cruz da Graciosa','Santa Cruz da Graciosa'),
            ('9800-543','Rua do Saco','Ilha de São Jorge','Velas','Velas'),
            ('9950-24','Rua 23 de Novembro','Ilha do Pico','Madalena','Bandeiras'),
            ('9900-370','Rua da Leonarda','Ilha do Faial','Horta','Feteira'),
            ('9900-452','Estrada General Humberto Delgado','Ilha do Faial','Horta','Praia')
]